
server:
  port: 8118

spring:
  #cache
  cache:
    type: redis
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: detect
  #jOOQ Configuration
  jooq:
    sql-dialect: mysql
  #spring.jackson.serialization.write_dates_as_timestamps=false
  jackson:
    serialization:
      write_dates_as_timestamps : false
  #spring.mobile.sitepreference.enabled: true
  mobile:
    sitepreference:
      enabled : true


  datasource:
    url: jdbc:mysql://rm-m5e41xelr0d8uvu78.mysql.rds.aliyuncs.com:3306/TNW?useSSL=false&createDatabaseIfNotExist=true
    username: lee5hx1
    password: 1XUhPgGNwpxv5Smx
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: 'SELECT 1'
      maximum-pool-size: 150
      #minimum-idle: 100
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

  #国际化
  messages:
    basename: i18n/messages
    cache-seconds: 3600
  boot:
    admin:
      url: http://localhost:8080

#日志log4j2
logging:
  config: /opt/jic-el/api/conf/logging-config.xml

# JWT
jwt:
  header: Authorization
  secret: fmOp9wZ0GnPojrBT
  expiration: 604800
  tokenHead: "JEL "
  route:
    authentication:
      login: auth
      refresh: "auth/refresh"
      register: "auth/register"


# management
management:
  port: 11111
  context-path: /admin
  security:
    enabled: false
    roles:



aliyunsms:
  api:
    accesskey-id: "LTAIIOgbRlQHECLw"
    accesskey-secret: "BsOOFE4rHVtL4iDXOj0Rf6AFgg3usJ"
    product: "Dysmsapi"
    domain: "dysmsapi.aliyuncs.com"


vaptcha:
  vid: "5a5822e6a48617214c19eb07"
  key: "6940042c97b646988f428ed0087059e5"

