/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * ???????
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Log implements Serializable {

    private static final long serialVersionUID = -1736173176;

    private Integer       id;
    private Integer       userId;
    private String        module;
    private String        action;
    private String        message;
    private String        data;
    private String        ip;
    private LocalDateTime createdTime;
    private String        level;

    public Log() {}

    public Log(Log value) {
        this.id = value.id;
        this.userId = value.userId;
        this.module = value.module;
        this.action = value.action;
        this.message = value.message;
        this.data = value.data;
        this.ip = value.ip;
        this.createdTime = value.createdTime;
        this.level = value.level;
    }

    public Log(
        Integer       id,
        Integer       userId,
        String        module,
        String        action,
        String        message,
        String        data,
        String        ip,
        LocalDateTime createdTime,
        String        level
    ) {
        this.id = id;
        this.userId = userId;
        this.module = module;
        this.action = action;
        this.message = message;
        this.data = data;
        this.ip = ip;
        this.createdTime = createdTime;
        this.level = level;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getModule() {
        return this.module;
    }

    public void setModule(String module) {
        this.module = module;
    }

    public String getAction() {
        return this.action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    public String getLevel() {
        return this.level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Log (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(module);
        sb.append(", ").append(action);
        sb.append(", ").append(message);
        sb.append(", ").append(data);
        sb.append(", ").append(ip);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(level);

        sb.append(")");
        return sb.toString();
    }
}
