/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.pojos;


import com.jic.tnw.db.mysql.enums.TasksStatus;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * ???
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tasks implements Serializable {

    private static final long serialVersionUID = -957740131;

    private Integer       id;
    private String        name;
    private LocalDateTime beginTime;
    private LocalDateTime endTime;
    private Long          elapsed;
    private String        triggedUserName;
    private TasksStatus   status;
    private String        result;

    public Tasks() {}

    public Tasks(Tasks value) {
        this.id = value.id;
        this.name = value.name;
        this.beginTime = value.beginTime;
        this.endTime = value.endTime;
        this.elapsed = value.elapsed;
        this.triggedUserName = value.triggedUserName;
        this.status = value.status;
        this.result = value.result;
    }

    public Tasks(
        Integer       id,
        String        name,
        LocalDateTime beginTime,
        LocalDateTime endTime,
        Long          elapsed,
        String        triggedUserName,
        TasksStatus   status,
        String        result
    ) {
        this.id = id;
        this.name = name;
        this.beginTime = beginTime;
        this.endTime = endTime;
        this.elapsed = elapsed;
        this.triggedUserName = triggedUserName;
        this.status = status;
        this.result = result;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDateTime getBeginTime() {
        return this.beginTime;
    }

    public void setBeginTime(LocalDateTime beginTime) {
        this.beginTime = beginTime;
    }

    public LocalDateTime getEndTime() {
        return this.endTime;
    }

    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    public Long getElapsed() {
        return this.elapsed;
    }

    public void setElapsed(Long elapsed) {
        this.elapsed = elapsed;
    }

    public String getTriggedUserName() {
        return this.triggedUserName;
    }

    public void setTriggedUserName(String triggedUserName) {
        this.triggedUserName = triggedUserName;
    }

    public TasksStatus getStatus() {
        return this.status;
    }

    public void setStatus(TasksStatus status) {
        this.status = status;
    }

    public String getResult() {
        return this.result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tasks (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(beginTime);
        sb.append(", ").append(endTime);
        sb.append(", ").append(elapsed);
        sb.append(", ").append(triggedUserName);
        sb.append(", ").append(status);
        sb.append(", ").append(result);

        sb.append(")");
        return sb.toString();
    }
}
