/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * ???
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroup implements Serializable {

    private static final long serialVersionUID = 1825979017;

    private Integer       id;
    private String        name;
    private String        description;
    private String        code;
    private Integer       createdUserId;
    private LocalDateTime createdTime;
    private Integer       lastUpdUserId;
    private LocalDateTime lastUpdTime;

    public UserGroup() {}

    public UserGroup(UserGroup value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.code = value.code;
        this.createdUserId = value.createdUserId;
        this.createdTime = value.createdTime;
        this.lastUpdUserId = value.lastUpdUserId;
        this.lastUpdTime = value.lastUpdTime;
    }

    public UserGroup(
        Integer       id,
        String        name,
        String        description,
        String        code,
        Integer       createdUserId,
        LocalDateTime createdTime,
        Integer       lastUpdUserId,
        LocalDateTime lastUpdTime
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.code = code;
        this.createdUserId = createdUserId;
        this.createdTime = createdTime;
        this.lastUpdUserId = lastUpdUserId;
        this.lastUpdTime = lastUpdTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Integer getCreatedUserId() {
        return this.createdUserId;
    }

    public void setCreatedUserId(Integer createdUserId) {
        this.createdUserId = createdUserId;
    }

    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    public Integer getLastUpdUserId() {
        return this.lastUpdUserId;
    }

    public void setLastUpdUserId(Integer lastUpdUserId) {
        this.lastUpdUserId = lastUpdUserId;
    }

    public LocalDateTime getLastUpdTime() {
        return this.lastUpdTime;
    }

    public void setLastUpdTime(LocalDateTime lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserGroup (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(code);
        sb.append(", ").append(createdUserId);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(lastUpdUserId);
        sb.append(", ").append(lastUpdTime);

        sb.append(")");
        return sb.toString();
    }
}
