/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.pojos;


import com.jic.tnw.db.mysql.enums.UserProfileGender;

import java.io.Serializable;
import java.sql.Date;
import java.time.LocalDate;

import javax.annotation.Generated;


/**
 * ?????
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserProfile implements Serializable {

    private static final long serialVersionUID = -1562370624;

    private Integer           id;
    private String            idcard;
    private UserProfileGender gender;
    private String            iam;
    private Date              birthday;
    private String            city;
    private String            qq;
    private String            signature;
    private String            about;
    private String            company;
    private String            job;
    private String            school;
    private String            class_;
    private String            weibo;
    private String            weixin;
    private Integer           isQqPublic;
    private Integer           isWeixinPublic;
    private Integer           isWeiboPublic;
    private String            site;
    private Integer           field1Int;
    private Integer           field2Int;
    private Integer           field3Int;
    private Integer           field4Int;
    private Integer           field5Int;
    private LocalDate         field1Date;
    private LocalDate         field2Date;
    private LocalDate         field3Date;
    private LocalDate         field4Date;
    private LocalDate         field5Date;
    private Double            field1Float;
    private Double            field2Float;
    private Double            field3Float;
    private Double            field4Float;
    private Double            field5Float;
    private String            field1Varchar;
    private String            field2Varchar;
    private String            field3Varchar;
    private String            field4Varchar;
    private String            field5Varchar;
    private String            field6Varchar;
    private String            field7Varchar;
    private String            field8Varchar;
    private String            field9Varchar;
    private String            field10Varchar;
    private String            field1Text;
    private String            field2Text;
    private String            field3Text;
    private String            field4Text;
    private String            field5Text;
    private String            field6Text;
    private String            field7Text;
    private String            field8Text;
    private String            field9Text;
    private String            field10Text;

    public UserProfile() {}

    public UserProfile(UserProfile value) {
        this.id = value.id;
        this.idcard = value.idcard;
        this.gender = value.gender;
        this.iam = value.iam;
        this.birthday = value.birthday;
        this.city = value.city;
        this.qq = value.qq;
        this.signature = value.signature;
        this.about = value.about;
        this.company = value.company;
        this.job = value.job;
        this.school = value.school;
        this.class_ = value.class_;
        this.weibo = value.weibo;
        this.weixin = value.weixin;
        this.isQqPublic = value.isQqPublic;
        this.isWeixinPublic = value.isWeixinPublic;
        this.isWeiboPublic = value.isWeiboPublic;
        this.site = value.site;
        this.field1Int = value.field1Int;
        this.field2Int = value.field2Int;
        this.field3Int = value.field3Int;
        this.field4Int = value.field4Int;
        this.field5Int = value.field5Int;
        this.field1Date = value.field1Date;
        this.field2Date = value.field2Date;
        this.field3Date = value.field3Date;
        this.field4Date = value.field4Date;
        this.field5Date = value.field5Date;
        this.field1Float = value.field1Float;
        this.field2Float = value.field2Float;
        this.field3Float = value.field3Float;
        this.field4Float = value.field4Float;
        this.field5Float = value.field5Float;
        this.field1Varchar = value.field1Varchar;
        this.field2Varchar = value.field2Varchar;
        this.field3Varchar = value.field3Varchar;
        this.field4Varchar = value.field4Varchar;
        this.field5Varchar = value.field5Varchar;
        this.field6Varchar = value.field6Varchar;
        this.field7Varchar = value.field7Varchar;
        this.field8Varchar = value.field8Varchar;
        this.field9Varchar = value.field9Varchar;
        this.field10Varchar = value.field10Varchar;
        this.field1Text = value.field1Text;
        this.field2Text = value.field2Text;
        this.field3Text = value.field3Text;
        this.field4Text = value.field4Text;
        this.field5Text = value.field5Text;
        this.field6Text = value.field6Text;
        this.field7Text = value.field7Text;
        this.field8Text = value.field8Text;
        this.field9Text = value.field9Text;
        this.field10Text = value.field10Text;
    }

    public UserProfile(
        Integer           id,
        String            idcard,
        UserProfileGender gender,
        String            iam,
        Date              birthday,
        String            city,
        String            qq,
        String            signature,
        String            about,
        String            company,
        String            job,
        String            school,
        String            class_,
        String            weibo,
        String            weixin,
        Integer           isQqPublic,
        Integer           isWeixinPublic,
        Integer           isWeiboPublic,
        String            site,
        Integer           field1Int,
        Integer           field2Int,
        Integer           field3Int,
        Integer           field4Int,
        Integer           field5Int,
        LocalDate         field1Date,
        LocalDate         field2Date,
        LocalDate         field3Date,
        LocalDate         field4Date,
        LocalDate         field5Date,
        Double            field1Float,
        Double            field2Float,
        Double            field3Float,
        Double            field4Float,
        Double            field5Float,
        String            field1Varchar,
        String            field2Varchar,
        String            field3Varchar,
        String            field4Varchar,
        String            field5Varchar,
        String            field6Varchar,
        String            field7Varchar,
        String            field8Varchar,
        String            field9Varchar,
        String            field10Varchar,
        String            field1Text,
        String            field2Text,
        String            field3Text,
        String            field4Text,
        String            field5Text,
        String            field6Text,
        String            field7Text,
        String            field8Text,
        String            field9Text,
        String            field10Text
    ) {
        this.id = id;
        this.idcard = idcard;
        this.gender = gender;
        this.iam = iam;
        this.birthday = birthday;
        this.city = city;
        this.qq = qq;
        this.signature = signature;
        this.about = about;
        this.company = company;
        this.job = job;
        this.school = school;
        this.class_ = class_;
        this.weibo = weibo;
        this.weixin = weixin;
        this.isQqPublic = isQqPublic;
        this.isWeixinPublic = isWeixinPublic;
        this.isWeiboPublic = isWeiboPublic;
        this.site = site;
        this.field1Int = field1Int;
        this.field2Int = field2Int;
        this.field3Int = field3Int;
        this.field4Int = field4Int;
        this.field5Int = field5Int;
        this.field1Date = field1Date;
        this.field2Date = field2Date;
        this.field3Date = field3Date;
        this.field4Date = field4Date;
        this.field5Date = field5Date;
        this.field1Float = field1Float;
        this.field2Float = field2Float;
        this.field3Float = field3Float;
        this.field4Float = field4Float;
        this.field5Float = field5Float;
        this.field1Varchar = field1Varchar;
        this.field2Varchar = field2Varchar;
        this.field3Varchar = field3Varchar;
        this.field4Varchar = field4Varchar;
        this.field5Varchar = field5Varchar;
        this.field6Varchar = field6Varchar;
        this.field7Varchar = field7Varchar;
        this.field8Varchar = field8Varchar;
        this.field9Varchar = field9Varchar;
        this.field10Varchar = field10Varchar;
        this.field1Text = field1Text;
        this.field2Text = field2Text;
        this.field3Text = field3Text;
        this.field4Text = field4Text;
        this.field5Text = field5Text;
        this.field6Text = field6Text;
        this.field7Text = field7Text;
        this.field8Text = field8Text;
        this.field9Text = field9Text;
        this.field10Text = field10Text;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getIdcard() {
        return this.idcard;
    }

    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    public UserProfileGender getGender() {
        return this.gender;
    }

    public void setGender(UserProfileGender gender) {
        this.gender = gender;
    }

    public String getIam() {
        return this.iam;
    }

    public void setIam(String iam) {
        this.iam = iam;
    }

    public Date getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getQq() {
        return this.qq;
    }

    public void setQq(String qq) {
        this.qq = qq;
    }

    public String getSignature() {
        return this.signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public String getAbout() {
        return this.about;
    }

    public void setAbout(String about) {
        this.about = about;
    }

    public String getCompany() {
        return this.company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getJob() {
        return this.job;
    }

    public void setJob(String job) {
        this.job = job;
    }

    public String getSchool() {
        return this.school;
    }

    public void setSchool(String school) {
        this.school = school;
    }

    public String getClass_() {
        return this.class_;
    }

    public void setClass_(String class_) {
        this.class_ = class_;
    }

    public String getWeibo() {
        return this.weibo;
    }

    public void setWeibo(String weibo) {
        this.weibo = weibo;
    }

    public String getWeixin() {
        return this.weixin;
    }

    public void setWeixin(String weixin) {
        this.weixin = weixin;
    }

    public Integer getIsQqPublic() {
        return this.isQqPublic;
    }

    public void setIsQqPublic(Integer isQqPublic) {
        this.isQqPublic = isQqPublic;
    }

    public Integer getIsWeixinPublic() {
        return this.isWeixinPublic;
    }

    public void setIsWeixinPublic(Integer isWeixinPublic) {
        this.isWeixinPublic = isWeixinPublic;
    }

    public Integer getIsWeiboPublic() {
        return this.isWeiboPublic;
    }

    public void setIsWeiboPublic(Integer isWeiboPublic) {
        this.isWeiboPublic = isWeiboPublic;
    }

    public String getSite() {
        return this.site;
    }

    public void setSite(String site) {
        this.site = site;
    }

    public Integer getField1Int() {
        return this.field1Int;
    }

    public void setField1Int(Integer field1Int) {
        this.field1Int = field1Int;
    }

    public Integer getField2Int() {
        return this.field2Int;
    }

    public void setField2Int(Integer field2Int) {
        this.field2Int = field2Int;
    }

    public Integer getField3Int() {
        return this.field3Int;
    }

    public void setField3Int(Integer field3Int) {
        this.field3Int = field3Int;
    }

    public Integer getField4Int() {
        return this.field4Int;
    }

    public void setField4Int(Integer field4Int) {
        this.field4Int = field4Int;
    }

    public Integer getField5Int() {
        return this.field5Int;
    }

    public void setField5Int(Integer field5Int) {
        this.field5Int = field5Int;
    }

    public LocalDate getField1Date() {
        return this.field1Date;
    }

    public void setField1Date(LocalDate field1Date) {
        this.field1Date = field1Date;
    }

    public LocalDate getField2Date() {
        return this.field2Date;
    }

    public void setField2Date(LocalDate field2Date) {
        this.field2Date = field2Date;
    }

    public LocalDate getField3Date() {
        return this.field3Date;
    }

    public void setField3Date(LocalDate field3Date) {
        this.field3Date = field3Date;
    }

    public LocalDate getField4Date() {
        return this.field4Date;
    }

    public void setField4Date(LocalDate field4Date) {
        this.field4Date = field4Date;
    }

    public LocalDate getField5Date() {
        return this.field5Date;
    }

    public void setField5Date(LocalDate field5Date) {
        this.field5Date = field5Date;
    }

    public Double getField1Float() {
        return this.field1Float;
    }

    public void setField1Float(Double field1Float) {
        this.field1Float = field1Float;
    }

    public Double getField2Float() {
        return this.field2Float;
    }

    public void setField2Float(Double field2Float) {
        this.field2Float = field2Float;
    }

    public Double getField3Float() {
        return this.field3Float;
    }

    public void setField3Float(Double field3Float) {
        this.field3Float = field3Float;
    }

    public Double getField4Float() {
        return this.field4Float;
    }

    public void setField4Float(Double field4Float) {
        this.field4Float = field4Float;
    }

    public Double getField5Float() {
        return this.field5Float;
    }

    public void setField5Float(Double field5Float) {
        this.field5Float = field5Float;
    }

    public String getField1Varchar() {
        return this.field1Varchar;
    }

    public void setField1Varchar(String field1Varchar) {
        this.field1Varchar = field1Varchar;
    }

    public String getField2Varchar() {
        return this.field2Varchar;
    }

    public void setField2Varchar(String field2Varchar) {
        this.field2Varchar = field2Varchar;
    }

    public String getField3Varchar() {
        return this.field3Varchar;
    }

    public void setField3Varchar(String field3Varchar) {
        this.field3Varchar = field3Varchar;
    }

    public String getField4Varchar() {
        return this.field4Varchar;
    }

    public void setField4Varchar(String field4Varchar) {
        this.field4Varchar = field4Varchar;
    }

    public String getField5Varchar() {
        return this.field5Varchar;
    }

    public void setField5Varchar(String field5Varchar) {
        this.field5Varchar = field5Varchar;
    }

    public String getField6Varchar() {
        return this.field6Varchar;
    }

    public void setField6Varchar(String field6Varchar) {
        this.field6Varchar = field6Varchar;
    }

    public String getField7Varchar() {
        return this.field7Varchar;
    }

    public void setField7Varchar(String field7Varchar) {
        this.field7Varchar = field7Varchar;
    }

    public String getField8Varchar() {
        return this.field8Varchar;
    }

    public void setField8Varchar(String field8Varchar) {
        this.field8Varchar = field8Varchar;
    }

    public String getField9Varchar() {
        return this.field9Varchar;
    }

    public void setField9Varchar(String field9Varchar) {
        this.field9Varchar = field9Varchar;
    }

    public String getField10Varchar() {
        return this.field10Varchar;
    }

    public void setField10Varchar(String field10Varchar) {
        this.field10Varchar = field10Varchar;
    }

    public String getField1Text() {
        return this.field1Text;
    }

    public void setField1Text(String field1Text) {
        this.field1Text = field1Text;
    }

    public String getField2Text() {
        return this.field2Text;
    }

    public void setField2Text(String field2Text) {
        this.field2Text = field2Text;
    }

    public String getField3Text() {
        return this.field3Text;
    }

    public void setField3Text(String field3Text) {
        this.field3Text = field3Text;
    }

    public String getField4Text() {
        return this.field4Text;
    }

    public void setField4Text(String field4Text) {
        this.field4Text = field4Text;
    }

    public String getField5Text() {
        return this.field5Text;
    }

    public void setField5Text(String field5Text) {
        this.field5Text = field5Text;
    }

    public String getField6Text() {
        return this.field6Text;
    }

    public void setField6Text(String field6Text) {
        this.field6Text = field6Text;
    }

    public String getField7Text() {
        return this.field7Text;
    }

    public void setField7Text(String field7Text) {
        this.field7Text = field7Text;
    }

    public String getField8Text() {
        return this.field8Text;
    }

    public void setField8Text(String field8Text) {
        this.field8Text = field8Text;
    }

    public String getField9Text() {
        return this.field9Text;
    }

    public void setField9Text(String field9Text) {
        this.field9Text = field9Text;
    }

    public String getField10Text() {
        return this.field10Text;
    }

    public void setField10Text(String field10Text) {
        this.field10Text = field10Text;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserProfile (");

        sb.append(id);
        sb.append(", ").append(idcard);
        sb.append(", ").append(gender);
        sb.append(", ").append(iam);
        sb.append(", ").append(birthday);
        sb.append(", ").append(city);
        sb.append(", ").append(qq);
        sb.append(", ").append(signature);
        sb.append(", ").append(about);
        sb.append(", ").append(company);
        sb.append(", ").append(job);
        sb.append(", ").append(school);
        sb.append(", ").append(class_);
        sb.append(", ").append(weibo);
        sb.append(", ").append(weixin);
        sb.append(", ").append(isQqPublic);
        sb.append(", ").append(isWeixinPublic);
        sb.append(", ").append(isWeiboPublic);
        sb.append(", ").append(site);
        sb.append(", ").append(field1Int);
        sb.append(", ").append(field2Int);
        sb.append(", ").append(field3Int);
        sb.append(", ").append(field4Int);
        sb.append(", ").append(field5Int);
        sb.append(", ").append(field1Date);
        sb.append(", ").append(field2Date);
        sb.append(", ").append(field3Date);
        sb.append(", ").append(field4Date);
        sb.append(", ").append(field5Date);
        sb.append(", ").append(field1Float);
        sb.append(", ").append(field2Float);
        sb.append(", ").append(field3Float);
        sb.append(", ").append(field4Float);
        sb.append(", ").append(field5Float);
        sb.append(", ").append(field1Varchar);
        sb.append(", ").append(field2Varchar);
        sb.append(", ").append(field3Varchar);
        sb.append(", ").append(field4Varchar);
        sb.append(", ").append(field5Varchar);
        sb.append(", ").append(field6Varchar);
        sb.append(", ").append(field7Varchar);
        sb.append(", ").append(field8Varchar);
        sb.append(", ").append(field9Varchar);
        sb.append(", ").append(field10Varchar);
        sb.append(", ").append(field1Text);
        sb.append(", ").append(field2Text);
        sb.append(", ").append(field3Text);
        sb.append(", ").append(field4Text);
        sb.append(", ").append(field5Text);
        sb.append(", ").append(field6Text);
        sb.append(", ").append(field7Text);
        sb.append(", ").append(field8Text);
        sb.append(", ").append(field9Text);
        sb.append(", ").append(field10Text);

        sb.append(")");
        return sb.toString();
    }
}
