/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.pojos;


import com.jic.tnw.db.mysql.enums.UserApprovalStatus;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * ???
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 2039068757;

    private Integer            id;
    private String             email;
    private String             mobile;
    private String             password;
    private String             payPassword;
    private String             locale;
    private String             uri;
    private String             username;
    private String             truename;
    private String             title;
    private String             tags;
    private String             type;
    private Integer            point;
    private Integer            coin;
    private String             smallAvatar;
    private String             mediumAvatar;
    private String             largeAvatar;
    private Boolean            emailVerified;
    private Boolean            setup;
    private String             roles;
    private Boolean            promoted;
    private Integer            promotedSeq;
    private LocalDateTime      promotedTime;
    private Boolean            locked;
    private Integer            lockDeadline;
    private Integer            consecutivePasswordErrorTimes;
    private LocalDateTime      lastPasswordFailTime;
    private LocalDateTime      lastPasswordResetTime;
    private LocalDateTime      loginTime;
    private String             loginIp;
    private String             loginSessionId;
    private LocalDateTime      approvalTime;
    private UserApprovalStatus approvalStatus;
    private Integer            newMessageNum;
    private Integer            newNotificationNum;
    private String             createdIp;
    private LocalDateTime      createdTime;
    private LocalDateTime      updatedTime;
    private String             inviteCode;
    private String             registeredWay;
    private Boolean            pwdInit;
    private Integer            postId;
    private Boolean            readGuide;
    private String             orgIds;
    private String             orgCodes;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.email = value.email;
        this.mobile = value.mobile;
        this.password = value.password;
        this.payPassword = value.payPassword;
        this.locale = value.locale;
        this.uri = value.uri;
        this.username = value.username;
        this.truename = value.truename;
        this.title = value.title;
        this.tags = value.tags;
        this.type = value.type;
        this.point = value.point;
        this.coin = value.coin;
        this.smallAvatar = value.smallAvatar;
        this.mediumAvatar = value.mediumAvatar;
        this.largeAvatar = value.largeAvatar;
        this.emailVerified = value.emailVerified;
        this.setup = value.setup;
        this.roles = value.roles;
        this.promoted = value.promoted;
        this.promotedSeq = value.promotedSeq;
        this.promotedTime = value.promotedTime;
        this.locked = value.locked;
        this.lockDeadline = value.lockDeadline;
        this.consecutivePasswordErrorTimes = value.consecutivePasswordErrorTimes;
        this.lastPasswordFailTime = value.lastPasswordFailTime;
        this.lastPasswordResetTime = value.lastPasswordResetTime;
        this.loginTime = value.loginTime;
        this.loginIp = value.loginIp;
        this.loginSessionId = value.loginSessionId;
        this.approvalTime = value.approvalTime;
        this.approvalStatus = value.approvalStatus;
        this.newMessageNum = value.newMessageNum;
        this.newNotificationNum = value.newNotificationNum;
        this.createdIp = value.createdIp;
        this.createdTime = value.createdTime;
        this.updatedTime = value.updatedTime;
        this.inviteCode = value.inviteCode;
        this.registeredWay = value.registeredWay;
        this.pwdInit = value.pwdInit;
        this.postId = value.postId;
        this.readGuide = value.readGuide;
        this.orgIds = value.orgIds;
        this.orgCodes = value.orgCodes;
    }

    public User(
        Integer            id,
        String             email,
        String             mobile,
        String             password,
        String             payPassword,
        String             locale,
        String             uri,
        String             username,
        String             truename,
        String             title,
        String             tags,
        String             type,
        Integer            point,
        Integer            coin,
        String             smallAvatar,
        String             mediumAvatar,
        String             largeAvatar,
        Boolean            emailVerified,
        Boolean            setup,
        String             roles,
        Boolean            promoted,
        Integer            promotedSeq,
        LocalDateTime      promotedTime,
        Boolean            locked,
        Integer            lockDeadline,
        Integer            consecutivePasswordErrorTimes,
        LocalDateTime      lastPasswordFailTime,
        LocalDateTime      lastPasswordResetTime,
        LocalDateTime      loginTime,
        String             loginIp,
        String             loginSessionId,
        LocalDateTime      approvalTime,
        UserApprovalStatus approvalStatus,
        Integer            newMessageNum,
        Integer            newNotificationNum,
        String             createdIp,
        LocalDateTime      createdTime,
        LocalDateTime      updatedTime,
        String             inviteCode,
        String             registeredWay,
        Boolean            pwdInit,
        Integer            postId,
        Boolean            readGuide,
        String             orgIds,
        String             orgCodes
    ) {
        this.id = id;
        this.email = email;
        this.mobile = mobile;
        this.password = password;
        this.payPassword = payPassword;
        this.locale = locale;
        this.uri = uri;
        this.username = username;
        this.truename = truename;
        this.title = title;
        this.tags = tags;
        this.type = type;
        this.point = point;
        this.coin = coin;
        this.smallAvatar = smallAvatar;
        this.mediumAvatar = mediumAvatar;
        this.largeAvatar = largeAvatar;
        this.emailVerified = emailVerified;
        this.setup = setup;
        this.roles = roles;
        this.promoted = promoted;
        this.promotedSeq = promotedSeq;
        this.promotedTime = promotedTime;
        this.locked = locked;
        this.lockDeadline = lockDeadline;
        this.consecutivePasswordErrorTimes = consecutivePasswordErrorTimes;
        this.lastPasswordFailTime = lastPasswordFailTime;
        this.lastPasswordResetTime = lastPasswordResetTime;
        this.loginTime = loginTime;
        this.loginIp = loginIp;
        this.loginSessionId = loginSessionId;
        this.approvalTime = approvalTime;
        this.approvalStatus = approvalStatus;
        this.newMessageNum = newMessageNum;
        this.newNotificationNum = newNotificationNum;
        this.createdIp = createdIp;
        this.createdTime = createdTime;
        this.updatedTime = updatedTime;
        this.inviteCode = inviteCode;
        this.registeredWay = registeredWay;
        this.pwdInit = pwdInit;
        this.postId = postId;
        this.readGuide = readGuide;
        this.orgIds = orgIds;
        this.orgCodes = orgCodes;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPayPassword() {
        return this.payPassword;
    }

    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword;
    }

    public String getLocale() {
        return this.locale;
    }

    public void setLocale(String locale) {
        this.locale = locale;
    }

    public String getUri() {
        return this.uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getTruename() {
        return this.truename;
    }

    public void setTruename(String truename) {
        this.truename = truename;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTags() {
        return this.tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getPoint() {
        return this.point;
    }

    public void setPoint(Integer point) {
        this.point = point;
    }

    public Integer getCoin() {
        return this.coin;
    }

    public void setCoin(Integer coin) {
        this.coin = coin;
    }

    public String getSmallAvatar() {
        return this.smallAvatar;
    }

    public void setSmallAvatar(String smallAvatar) {
        this.smallAvatar = smallAvatar;
    }

    public String getMediumAvatar() {
        return this.mediumAvatar;
    }

    public void setMediumAvatar(String mediumAvatar) {
        this.mediumAvatar = mediumAvatar;
    }

    public String getLargeAvatar() {
        return this.largeAvatar;
    }

    public void setLargeAvatar(String largeAvatar) {
        this.largeAvatar = largeAvatar;
    }

    public Boolean getEmailVerified() {
        return this.emailVerified;
    }

    public void setEmailVerified(Boolean emailVerified) {
        this.emailVerified = emailVerified;
    }

    public Boolean getSetup() {
        return this.setup;
    }

    public void setSetup(Boolean setup) {
        this.setup = setup;
    }

    public String getRoles() {
        return this.roles;
    }

    public void setRoles(String roles) {
        this.roles = roles;
    }

    public Boolean getPromoted() {
        return this.promoted;
    }

    public void setPromoted(Boolean promoted) {
        this.promoted = promoted;
    }

    public Integer getPromotedSeq() {
        return this.promotedSeq;
    }

    public void setPromotedSeq(Integer promotedSeq) {
        this.promotedSeq = promotedSeq;
    }

    public LocalDateTime getPromotedTime() {
        return this.promotedTime;
    }

    public void setPromotedTime(LocalDateTime promotedTime) {
        this.promotedTime = promotedTime;
    }

    public Boolean getLocked() {
        return this.locked;
    }

    public void setLocked(Boolean locked) {
        this.locked = locked;
    }

    public Integer getLockDeadline() {
        return this.lockDeadline;
    }

    public void setLockDeadline(Integer lockDeadline) {
        this.lockDeadline = lockDeadline;
    }

    public Integer getConsecutivePasswordErrorTimes() {
        return this.consecutivePasswordErrorTimes;
    }

    public void setConsecutivePasswordErrorTimes(Integer consecutivePasswordErrorTimes) {
        this.consecutivePasswordErrorTimes = consecutivePasswordErrorTimes;
    }

    public LocalDateTime getLastPasswordFailTime() {
        return this.lastPasswordFailTime;
    }

    public void setLastPasswordFailTime(LocalDateTime lastPasswordFailTime) {
        this.lastPasswordFailTime = lastPasswordFailTime;
    }

    public LocalDateTime getLastPasswordResetTime() {
        return this.lastPasswordResetTime;
    }

    public void setLastPasswordResetTime(LocalDateTime lastPasswordResetTime) {
        this.lastPasswordResetTime = lastPasswordResetTime;
    }

    public LocalDateTime getLoginTime() {
        return this.loginTime;
    }

    public void setLoginTime(LocalDateTime loginTime) {
        this.loginTime = loginTime;
    }

    public String getLoginIp() {
        return this.loginIp;
    }

    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    public String getLoginSessionId() {
        return this.loginSessionId;
    }

    public void setLoginSessionId(String loginSessionId) {
        this.loginSessionId = loginSessionId;
    }

    public LocalDateTime getApprovalTime() {
        return this.approvalTime;
    }

    public void setApprovalTime(LocalDateTime approvalTime) {
        this.approvalTime = approvalTime;
    }

    public UserApprovalStatus getApprovalStatus() {
        return this.approvalStatus;
    }

    public void setApprovalStatus(UserApprovalStatus approvalStatus) {
        this.approvalStatus = approvalStatus;
    }

    public Integer getNewMessageNum() {
        return this.newMessageNum;
    }

    public void setNewMessageNum(Integer newMessageNum) {
        this.newMessageNum = newMessageNum;
    }

    public Integer getNewNotificationNum() {
        return this.newNotificationNum;
    }

    public void setNewNotificationNum(Integer newNotificationNum) {
        this.newNotificationNum = newNotificationNum;
    }

    public String getCreatedIp() {
        return this.createdIp;
    }

    public void setCreatedIp(String createdIp) {
        this.createdIp = createdIp;
    }

    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    public LocalDateTime getUpdatedTime() {
        return this.updatedTime;
    }

    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }

    public String getInviteCode() {
        return this.inviteCode;
    }

    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode;
    }

    public String getRegisteredWay() {
        return this.registeredWay;
    }

    public void setRegisteredWay(String registeredWay) {
        this.registeredWay = registeredWay;
    }

    public Boolean getPwdInit() {
        return this.pwdInit;
    }

    public void setPwdInit(Boolean pwdInit) {
        this.pwdInit = pwdInit;
    }

    public Integer getPostId() {
        return this.postId;
    }

    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    public Boolean getReadGuide() {
        return this.readGuide;
    }

    public void setReadGuide(Boolean readGuide) {
        this.readGuide = readGuide;
    }

    public String getOrgIds() {
        return this.orgIds;
    }

    public void setOrgIds(String orgIds) {
        this.orgIds = orgIds;
    }

    public String getOrgCodes() {
        return this.orgCodes;
    }

    public void setOrgCodes(String orgCodes) {
        this.orgCodes = orgCodes;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(mobile);
        sb.append(", ").append(password);
        sb.append(", ").append(payPassword);
        sb.append(", ").append(locale);
        sb.append(", ").append(uri);
        sb.append(", ").append(username);
        sb.append(", ").append(truename);
        sb.append(", ").append(title);
        sb.append(", ").append(tags);
        sb.append(", ").append(type);
        sb.append(", ").append(point);
        sb.append(", ").append(coin);
        sb.append(", ").append(smallAvatar);
        sb.append(", ").append(mediumAvatar);
        sb.append(", ").append(largeAvatar);
        sb.append(", ").append(emailVerified);
        sb.append(", ").append(setup);
        sb.append(", ").append(roles);
        sb.append(", ").append(promoted);
        sb.append(", ").append(promotedSeq);
        sb.append(", ").append(promotedTime);
        sb.append(", ").append(locked);
        sb.append(", ").append(lockDeadline);
        sb.append(", ").append(consecutivePasswordErrorTimes);
        sb.append(", ").append(lastPasswordFailTime);
        sb.append(", ").append(lastPasswordResetTime);
        sb.append(", ").append(loginTime);
        sb.append(", ").append(loginIp);
        sb.append(", ").append(loginSessionId);
        sb.append(", ").append(approvalTime);
        sb.append(", ").append(approvalStatus);
        sb.append(", ").append(newMessageNum);
        sb.append(", ").append(newNotificationNum);
        sb.append(", ").append(createdIp);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(updatedTime);
        sb.append(", ").append(inviteCode);
        sb.append(", ").append(registeredWay);
        sb.append(", ").append(pwdInit);
        sb.append(", ").append(postId);
        sb.append(", ").append(readGuide);
        sb.append(", ").append(orgIds);
        sb.append(", ").append(orgCodes);

        sb.append(")");
        return sb.toString();
    }
}
