/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.pojos;


import com.jic.tnw.db.mysql.enums.UserGroupMemberMemberType;

import javax.annotation.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * ?????
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupMember implements Serializable {

    private static final long serialVersionUID = 1355344538;

    private Integer                   id;
    private Integer                   groupId;
    private Integer                   memberId;
    private UserGroupMemberMemberType memberType;
    private Integer                   createdUserId;
    private LocalDateTime             createdTime;
    private Integer                   lastUpdUserId;
    private LocalDateTime             lastUpdTime;

    public UserGroupMember() {}

    public UserGroupMember(UserGroupMember value) {
        this.id = value.id;
        this.groupId = value.groupId;
        this.memberId = value.memberId;
        this.memberType = value.memberType;
        this.createdUserId = value.createdUserId;
        this.createdTime = value.createdTime;
        this.lastUpdUserId = value.lastUpdUserId;
        this.lastUpdTime = value.lastUpdTime;
    }

    public UserGroupMember(
        Integer                   id,
        Integer                   groupId,
        Integer                   memberId,
        UserGroupMemberMemberType memberType,
        Integer                   createdUserId,
        LocalDateTime             createdTime,
        Integer                   lastUpdUserId,
        LocalDateTime             lastUpdTime
    ) {
        this.id = id;
        this.groupId = groupId;
        this.memberId = memberId;
        this.memberType = memberType;
        this.createdUserId = createdUserId;
        this.createdTime = createdTime;
        this.lastUpdUserId = lastUpdUserId;
        this.lastUpdTime = lastUpdTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public Integer getMemberId() {
        return this.memberId;
    }

    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    public UserGroupMemberMemberType getMemberType() {
        return this.memberType;
    }

    public void setMemberType(UserGroupMemberMemberType memberType) {
        this.memberType = memberType;
    }

    public Integer getCreatedUserId() {
        return this.createdUserId;
    }

    public void setCreatedUserId(Integer createdUserId) {
        this.createdUserId = createdUserId;
    }

    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    public Integer getLastUpdUserId() {
        return this.lastUpdUserId;
    }

    public void setLastUpdUserId(Integer lastUpdUserId) {
        this.lastUpdUserId = lastUpdUserId;
    }

    public LocalDateTime getLastUpdTime() {
        return this.lastUpdTime;
    }

    public void setLastUpdTime(LocalDateTime lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserGroupMember (");

        sb.append(id);
        sb.append(", ").append(groupId);
        sb.append(", ").append(memberId);
        sb.append(", ").append(memberType);
        sb.append(", ").append(createdUserId);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(lastUpdUserId);
        sb.append(", ").append(lastUpdTime);

        sb.append(")");
        return sb.toString();
    }
}
