/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql;


import com.jic.tnw.db.mysql.tables.Log;
import com.jic.tnw.db.mysql.tables.Org;
import com.jic.tnw.db.mysql.tables.Post;
import com.jic.tnw.db.mysql.tables.PostGroup;
import com.jic.tnw.db.mysql.tables.PostMember;
import com.jic.tnw.db.mysql.tables.Role;
import com.jic.tnw.db.mysql.tables.Tasks;
import com.jic.tnw.db.mysql.tables.User;
import com.jic.tnw.db.mysql.tables.UserGroup;
import com.jic.tnw.db.mysql.tables.UserGroupMember;
import com.jic.tnw.db.mysql.tables.UserOrg;
import com.jic.tnw.db.mysql.tables.UserProfile;
import com.jic.tnw.db.mysql.tables.WebUrlResource;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>TNW</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index LOG_PRIMARY = Indexes0.LOG_PRIMARY;
    public static final Index LOG_USERID = Indexes0.LOG_USERID;
    public static final Index ORG_CODE = Indexes0.ORG_CODE;
    public static final Index ORG_ORG_CODE = Indexes0.ORG_ORG_CODE;
    public static final Index ORG_PRIMARY = Indexes0.ORG_PRIMARY;
    public static final Index POST_PRIMARY = Indexes0.POST_PRIMARY;
    public static final Index POST_GROUP_PRIMARY = Indexes0.POST_GROUP_PRIMARY;
    public static final Index POST_MEMBER_PRIMARY = Indexes0.POST_MEMBER_PRIMARY;
    public static final Index ROLE_PRIMARY = Indexes0.ROLE_PRIMARY;
    public static final Index TASKS_PRIMARY = Indexes0.TASKS_PRIMARY;
    public static final Index TASKS_TASKS_NAME_INDEX = Indexes0.TASKS_TASKS_NAME_INDEX;
    public static final Index TASKS_TASKS_STATUS_INDEX = Indexes0.TASKS_TASKS_STATUS_INDEX;
    public static final Index TASKS_TASKS_TRIGGED_USER_NAME_INDEX = Indexes0.TASKS_TASKS_TRIGGED_USER_NAME_INDEX;
    public static final Index USER_EMAIL_INDEX = Indexes0.USER_EMAIL_INDEX;
    public static final Index USER_MOBILE_INDEX = Indexes0.USER_MOBILE_INDEX;
    public static final Index USER_ORG_CODES_INDEX = Indexes0.USER_ORG_CODES_INDEX;
    public static final Index USER_ORG_POST_ID_INDEX = Indexes0.USER_ORG_POST_ID_INDEX;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;
    public static final Index USER_PROMOTED = Indexes0.USER_PROMOTED;
    public static final Index USER_UPDATEDTIME = Indexes0.USER_UPDATEDTIME;
    public static final Index USER_USERNAME = Indexes0.USER_USERNAME;
    public static final Index USER_USER_TYPE_INDEX = Indexes0.USER_USER_TYPE_INDEX;
    public static final Index USER_GROUP_CODE = Indexes0.USER_GROUP_CODE;
    public static final Index USER_GROUP_PRIMARY = Indexes0.USER_GROUP_PRIMARY;
    public static final Index USER_GROUP_MEMBER_PRIMARY = Indexes0.USER_GROUP_MEMBER_PRIMARY;
    public static final Index USER_ORG_PRIMARY = Indexes0.USER_ORG_PRIMARY;
    public static final Index USER_PROFILE_PRIMARY = Indexes0.USER_PROFILE_PRIMARY;
    public static final Index WEB_URL_RESOURCE_PRIMARY = Indexes0.WEB_URL_RESOURCE_PRIMARY;
    public static final Index WEB_URL_RESOURCE_WEB_URL_RESOURCE_CODE_INDEX = Indexes0.WEB_URL_RESOURCE_WEB_URL_RESOURCE_CODE_INDEX;
    public static final Index WEB_URL_RESOURCE_WEB_URL_RESOURCE_TYPE_INDEX = Indexes0.WEB_URL_RESOURCE_WEB_URL_RESOURCE_TYPE_INDEX;
    public static final Index WEB_URL_RESOURCE_WUR_CODE_IDX = Indexes0.WEB_URL_RESOURCE_WUR_CODE_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index LOG_PRIMARY = createIndex("PRIMARY", Log.LOG, new OrderField[] { Log.LOG.ID }, true);
        public static Index LOG_USERID = createIndex("userId", Log.LOG, new OrderField[] { Log.LOG.USER_ID }, false);
        public static Index ORG_CODE = createIndex("code", Org.ORG, new OrderField[] { Org.ORG.CODE }, true);
        public static Index ORG_ORG_CODE = createIndex("org_code", Org.ORG, new OrderField[] { Org.ORG.ORG_CODE }, true);
        public static Index ORG_PRIMARY = createIndex("PRIMARY", Org.ORG, new OrderField[] { Org.ORG.ID }, true);
        public static Index POST_PRIMARY = createIndex("PRIMARY", Post.POST, new OrderField[] { Post.POST.ID }, true);
        public static Index POST_GROUP_PRIMARY = createIndex("PRIMARY", PostGroup.POST_GROUP, new OrderField[] { PostGroup.POST_GROUP.ID }, true);
        public static Index POST_MEMBER_PRIMARY = createIndex("PRIMARY", PostMember.POST_MEMBER, new OrderField[] { PostMember.POST_MEMBER.ID }, true);
        public static Index ROLE_PRIMARY = createIndex("PRIMARY", Role.ROLE, new OrderField[] { Role.ROLE.ID }, true);
        public static Index TASKS_PRIMARY = createIndex("PRIMARY", Tasks.TASKS, new OrderField[] { Tasks.TASKS.ID }, true);
        public static Index TASKS_TASKS_NAME_INDEX = createIndex("tasks_name_index", Tasks.TASKS, new OrderField[] { Tasks.TASKS.NAME }, false);
        public static Index TASKS_TASKS_STATUS_INDEX = createIndex("tasks_status_index", Tasks.TASKS, new OrderField[] { Tasks.TASKS.STATUS }, false);
        public static Index TASKS_TASKS_TRIGGED_USER_NAME_INDEX = createIndex("tasks_trigged_user_name_index", Tasks.TASKS, new OrderField[] { Tasks.TASKS.TRIGGED_USER_NAME }, false);
        public static Index USER_EMAIL_INDEX = createIndex("email_index", User.USER, new OrderField[] { User.USER.EMAIL }, false);
        public static Index USER_MOBILE_INDEX = createIndex("mobile_index", User.USER, new OrderField[] { User.USER.MOBILE }, false);
        public static Index USER_ORG_CODES_INDEX = createIndex("org_codes_index", User.USER, new OrderField[] { User.USER.ORG_CODES }, false);
        public static Index USER_ORG_POST_ID_INDEX = createIndex("org_post_id_index", User.USER, new OrderField[] { User.USER.POST_ID }, false);
        public static Index USER_PRIMARY = createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_PROMOTED = createIndex("promoted", User.USER, new OrderField[] { User.USER.PROMOTED }, false);
        public static Index USER_UPDATEDTIME = createIndex("updatedTime", User.USER, new OrderField[] { User.USER.UPDATED_TIME }, false);
        public static Index USER_USERNAME = createIndex("username", User.USER, new OrderField[] { User.USER.USERNAME }, true);
        public static Index USER_USER_TYPE_INDEX = createIndex("user_type_index", User.USER, new OrderField[] { User.USER.TYPE }, false);
        public static Index USER_GROUP_CODE = createIndex("code", UserGroup.USER_GROUP, new OrderField[] { UserGroup.USER_GROUP.CODE }, true);
        public static Index USER_GROUP_PRIMARY = createIndex("PRIMARY", UserGroup.USER_GROUP, new OrderField[] { UserGroup.USER_GROUP.ID }, true);
        public static Index USER_GROUP_MEMBER_PRIMARY = createIndex("PRIMARY", UserGroupMember.USER_GROUP_MEMBER, new OrderField[] { UserGroupMember.USER_GROUP_MEMBER.ID }, true);
        public static Index USER_ORG_PRIMARY = createIndex("PRIMARY", UserOrg.USER_ORG, new OrderField[] { UserOrg.USER_ORG.ID }, true);
        public static Index USER_PROFILE_PRIMARY = createIndex("PRIMARY", UserProfile.USER_PROFILE, new OrderField[] { UserProfile.USER_PROFILE.ID }, true);
        public static Index WEB_URL_RESOURCE_PRIMARY = createIndex("PRIMARY", WebUrlResource.WEB_URL_RESOURCE, new OrderField[] { WebUrlResource.WEB_URL_RESOURCE.ID }, true);
        public static Index WEB_URL_RESOURCE_WEB_URL_RESOURCE_CODE_INDEX = createIndex("web_url_resource_code_index", WebUrlResource.WEB_URL_RESOURCE, new OrderField[] { WebUrlResource.WEB_URL_RESOURCE.CODE }, false);
        public static Index WEB_URL_RESOURCE_WEB_URL_RESOURCE_TYPE_INDEX = createIndex("web_url_resource_type_index", WebUrlResource.WEB_URL_RESOURCE, new OrderField[] { WebUrlResource.WEB_URL_RESOURCE.TYPE }, false);
        public static Index WEB_URL_RESOURCE_WUR_CODE_IDX = createIndex("wur_code_idx", WebUrlResource.WEB_URL_RESOURCE, new OrderField[] { WebUrlResource.WEB_URL_RESOURCE.WUR_CODE }, false);
    }
}
