/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql;


import com.jic.tnw.db.mysql.tables.Log;
import com.jic.tnw.db.mysql.tables.Org;
import com.jic.tnw.db.mysql.tables.Post;
import com.jic.tnw.db.mysql.tables.PostGroup;
import com.jic.tnw.db.mysql.tables.PostMember;
import com.jic.tnw.db.mysql.tables.Role;
import com.jic.tnw.db.mysql.tables.Tasks;
import com.jic.tnw.db.mysql.tables.User;
import com.jic.tnw.db.mysql.tables.UserGroup;
import com.jic.tnw.db.mysql.tables.UserGroupMember;
import com.jic.tnw.db.mysql.tables.UserOrg;
import com.jic.tnw.db.mysql.tables.UserProfile;
import com.jic.tnw.db.mysql.tables.WebUrlResource;
import com.jic.tnw.db.mysql.tables.records.LogRecord;
import com.jic.tnw.db.mysql.tables.records.OrgRecord;
import com.jic.tnw.db.mysql.tables.records.PostGroupRecord;
import com.jic.tnw.db.mysql.tables.records.PostMemberRecord;
import com.jic.tnw.db.mysql.tables.records.PostRecord;
import com.jic.tnw.db.mysql.tables.records.RoleRecord;
import com.jic.tnw.db.mysql.tables.records.TasksRecord;
import com.jic.tnw.db.mysql.tables.records.UserGroupMemberRecord;
import com.jic.tnw.db.mysql.tables.records.UserGroupRecord;
import com.jic.tnw.db.mysql.tables.records.UserOrgRecord;
import com.jic.tnw.db.mysql.tables.records.UserProfileRecord;
import com.jic.tnw.db.mysql.tables.records.UserRecord;
import com.jic.tnw.db.mysql.tables.records.WebUrlResourceRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>TNW</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<LogRecord, Integer> IDENTITY_LOG = Identities0.IDENTITY_LOG;
    public static final Identity<OrgRecord, Integer> IDENTITY_ORG = Identities0.IDENTITY_ORG;
    public static final Identity<PostRecord, Integer> IDENTITY_POST = Identities0.IDENTITY_POST;
    public static final Identity<PostGroupRecord, Integer> IDENTITY_POST_GROUP = Identities0.IDENTITY_POST_GROUP;
    public static final Identity<PostMemberRecord, Integer> IDENTITY_POST_MEMBER = Identities0.IDENTITY_POST_MEMBER;
    public static final Identity<RoleRecord, Integer> IDENTITY_ROLE = Identities0.IDENTITY_ROLE;
    public static final Identity<TasksRecord, Integer> IDENTITY_TASKS = Identities0.IDENTITY_TASKS;
    public static final Identity<UserRecord, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;
    public static final Identity<UserGroupRecord, Integer> IDENTITY_USER_GROUP = Identities0.IDENTITY_USER_GROUP;
    public static final Identity<UserGroupMemberRecord, Integer> IDENTITY_USER_GROUP_MEMBER = Identities0.IDENTITY_USER_GROUP_MEMBER;
    public static final Identity<UserOrgRecord, Integer> IDENTITY_USER_ORG = Identities0.IDENTITY_USER_ORG;
    public static final Identity<WebUrlResourceRecord, Integer> IDENTITY_WEB_URL_RESOURCE = Identities0.IDENTITY_WEB_URL_RESOURCE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LogRecord> KEY_LOG_PRIMARY = UniqueKeys0.KEY_LOG_PRIMARY;
    public static final UniqueKey<OrgRecord> KEY_ORG_PRIMARY = UniqueKeys0.KEY_ORG_PRIMARY;
    public static final UniqueKey<OrgRecord> KEY_ORG_CODE = UniqueKeys0.KEY_ORG_CODE;
    public static final UniqueKey<OrgRecord> KEY_ORG_ORG_CODE = UniqueKeys0.KEY_ORG_ORG_CODE;
    public static final UniqueKey<PostRecord> KEY_POST_PRIMARY = UniqueKeys0.KEY_POST_PRIMARY;
    public static final UniqueKey<PostGroupRecord> KEY_POST_GROUP_PRIMARY = UniqueKeys0.KEY_POST_GROUP_PRIMARY;
    public static final UniqueKey<PostMemberRecord> KEY_POST_MEMBER_PRIMARY = UniqueKeys0.KEY_POST_MEMBER_PRIMARY;
    public static final UniqueKey<RoleRecord> KEY_ROLE_PRIMARY = UniqueKeys0.KEY_ROLE_PRIMARY;
    public static final UniqueKey<TasksRecord> KEY_TASKS_PRIMARY = UniqueKeys0.KEY_TASKS_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_USERNAME = UniqueKeys0.KEY_USER_USERNAME;
    public static final UniqueKey<UserGroupRecord> KEY_USER_GROUP_PRIMARY = UniqueKeys0.KEY_USER_GROUP_PRIMARY;
    public static final UniqueKey<UserGroupRecord> KEY_USER_GROUP_CODE = UniqueKeys0.KEY_USER_GROUP_CODE;
    public static final UniqueKey<UserGroupMemberRecord> KEY_USER_GROUP_MEMBER_PRIMARY = UniqueKeys0.KEY_USER_GROUP_MEMBER_PRIMARY;
    public static final UniqueKey<UserOrgRecord> KEY_USER_ORG_PRIMARY = UniqueKeys0.KEY_USER_ORG_PRIMARY;
    public static final UniqueKey<UserProfileRecord> KEY_USER_PROFILE_PRIMARY = UniqueKeys0.KEY_USER_PROFILE_PRIMARY;
    public static final UniqueKey<WebUrlResourceRecord> KEY_WEB_URL_RESOURCE_PRIMARY = UniqueKeys0.KEY_WEB_URL_RESOURCE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<LogRecord, Integer> IDENTITY_LOG = createIdentity(Log.LOG, Log.LOG.ID);
        public static Identity<OrgRecord, Integer> IDENTITY_ORG = createIdentity(Org.ORG, Org.ORG.ID);
        public static Identity<PostRecord, Integer> IDENTITY_POST = createIdentity(Post.POST, Post.POST.ID);
        public static Identity<PostGroupRecord, Integer> IDENTITY_POST_GROUP = createIdentity(PostGroup.POST_GROUP, PostGroup.POST_GROUP.ID);
        public static Identity<PostMemberRecord, Integer> IDENTITY_POST_MEMBER = createIdentity(PostMember.POST_MEMBER, PostMember.POST_MEMBER.ID);
        public static Identity<RoleRecord, Integer> IDENTITY_ROLE = createIdentity(Role.ROLE, Role.ROLE.ID);
        public static Identity<TasksRecord, Integer> IDENTITY_TASKS = createIdentity(Tasks.TASKS, Tasks.TASKS.ID);
        public static Identity<UserRecord, Integer> IDENTITY_USER = createIdentity(User.USER, User.USER.ID);
        public static Identity<UserGroupRecord, Integer> IDENTITY_USER_GROUP = createIdentity(UserGroup.USER_GROUP, UserGroup.USER_GROUP.ID);
        public static Identity<UserGroupMemberRecord, Integer> IDENTITY_USER_GROUP_MEMBER = createIdentity(UserGroupMember.USER_GROUP_MEMBER, UserGroupMember.USER_GROUP_MEMBER.ID);
        public static Identity<UserOrgRecord, Integer> IDENTITY_USER_ORG = createIdentity(UserOrg.USER_ORG, UserOrg.USER_ORG.ID);
        public static Identity<WebUrlResourceRecord, Integer> IDENTITY_WEB_URL_RESOURCE = createIdentity(WebUrlResource.WEB_URL_RESOURCE, WebUrlResource.WEB_URL_RESOURCE.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<LogRecord> KEY_LOG_PRIMARY = createUniqueKey(Log.LOG, "KEY_log_PRIMARY", Log.LOG.ID);
        public static final UniqueKey<OrgRecord> KEY_ORG_PRIMARY = createUniqueKey(Org.ORG, "KEY_org_PRIMARY", Org.ORG.ID);
        public static final UniqueKey<OrgRecord> KEY_ORG_CODE = createUniqueKey(Org.ORG, "KEY_org_code", Org.ORG.CODE);
        public static final UniqueKey<OrgRecord> KEY_ORG_ORG_CODE = createUniqueKey(Org.ORG, "KEY_org_org_code", Org.ORG.ORG_CODE);
        public static final UniqueKey<PostRecord> KEY_POST_PRIMARY = createUniqueKey(Post.POST, "KEY_post_PRIMARY", Post.POST.ID);
        public static final UniqueKey<PostGroupRecord> KEY_POST_GROUP_PRIMARY = createUniqueKey(PostGroup.POST_GROUP, "KEY_post_group_PRIMARY", PostGroup.POST_GROUP.ID);
        public static final UniqueKey<PostMemberRecord> KEY_POST_MEMBER_PRIMARY = createUniqueKey(PostMember.POST_MEMBER, "KEY_post_member_PRIMARY", PostMember.POST_MEMBER.ID);
        public static final UniqueKey<RoleRecord> KEY_ROLE_PRIMARY = createUniqueKey(Role.ROLE, "KEY_role_PRIMARY", Role.ROLE.ID);
        public static final UniqueKey<TasksRecord> KEY_TASKS_PRIMARY = createUniqueKey(Tasks.TASKS, "KEY_tasks_PRIMARY", Tasks.TASKS.ID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
        public static final UniqueKey<UserRecord> KEY_USER_USERNAME = createUniqueKey(User.USER, "KEY_user_username", User.USER.USERNAME);
        public static final UniqueKey<UserGroupRecord> KEY_USER_GROUP_PRIMARY = createUniqueKey(UserGroup.USER_GROUP, "KEY_user_group_PRIMARY", UserGroup.USER_GROUP.ID);
        public static final UniqueKey<UserGroupRecord> KEY_USER_GROUP_CODE = createUniqueKey(UserGroup.USER_GROUP, "KEY_user_group_code", UserGroup.USER_GROUP.CODE);
        public static final UniqueKey<UserGroupMemberRecord> KEY_USER_GROUP_MEMBER_PRIMARY = createUniqueKey(UserGroupMember.USER_GROUP_MEMBER, "KEY_user_group_member_PRIMARY", UserGroupMember.USER_GROUP_MEMBER.ID);
        public static final UniqueKey<UserOrgRecord> KEY_USER_ORG_PRIMARY = createUniqueKey(UserOrg.USER_ORG, "KEY_user_org_PRIMARY", UserOrg.USER_ORG.ID);
        public static final UniqueKey<UserProfileRecord> KEY_USER_PROFILE_PRIMARY = createUniqueKey(UserProfile.USER_PROFILE, "KEY_user_profile_PRIMARY", UserProfile.USER_PROFILE.ID);
        public static final UniqueKey<WebUrlResourceRecord> KEY_WEB_URL_RESOURCE_PRIMARY = createUniqueKey(WebUrlResource.WEB_URL_RESOURCE, "KEY_web_url_resource_PRIMARY", WebUrlResource.WEB_URL_RESOURCE.ID);
    }
}
