/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql;


import com.jic.tnw.db.mysql.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tnw extends SchemaImpl {

    private static final long serialVersionUID = -1862559616;

    /**
     * The reference instance of <code>TNW</code>
     */
    public static final Tnw TNW = new Tnw();

    /**
     * ????
     */
    public final DwComment DW_COMMENT = com.jic.tnw.db.mysql.tables.DwComment.DW_COMMENT;

    /**
     * ????
     */
    public final DwFabulous DW_FABULOUS = com.jic.tnw.db.mysql.tables.DwFabulous.DW_FABULOUS;

    /**
     * ???
     */
    public final DwMyMessage DW_MY_MESSAGE = com.jic.tnw.db.mysql.tables.DwMyMessage.DW_MY_MESSAGE;

    /**
     * ?????
     */
    public final DwOldActivity DW_OLD_ACTIVITY = com.jic.tnw.db.mysql.tables.DwOldActivity.DW_OLD_ACTIVITY;

    /**
     * ?????
     */
    public final DwOrgcircleActivity DW_ORGCIRCLE_ACTIVITY = com.jic.tnw.db.mysql.tables.DwOrgcircleActivity.DW_ORGCIRCLE_ACTIVITY;

    /**
     * ?????
     */
    public final DwOrgcircleDynamic DW_ORGCIRCLE_DYNAMIC = com.jic.tnw.db.mysql.tables.DwOrgcircleDynamic.DW_ORGCIRCLE_DYNAMIC;

    /**
     * ???
     */
    public final DwOtherMessage DW_OTHER_MESSAGE = com.jic.tnw.db.mysql.tables.DwOtherMessage.DW_OTHER_MESSAGE;

    /**
     * The table <code>TNW.dw_ranking_compete</code>.
     */
    public final DwRankingCompete DW_RANKING_COMPETE = com.jic.tnw.db.mysql.tables.DwRankingCompete.DW_RANKING_COMPETE;

    /**
     * The table <code>TNW.dw_ranking_comprehensive</code>.
     */
    public final DwRankingComprehensive DW_RANKING_COMPREHENSIVE = com.jic.tnw.db.mysql.tables.DwRankingComprehensive.DW_RANKING_COMPREHENSIVE;

    /**
     * The table <code>TNW.dw_ranking_detail</code>.
     */
    public final DwRankingDetail DW_RANKING_DETAIL = com.jic.tnw.db.mysql.tables.DwRankingDetail.DW_RANKING_DETAIL;

    /**
     * The table <code>TNW.dw_ranking_profit</code>.
     */
    public final DwRankingProfit DW_RANKING_PROFIT = com.jic.tnw.db.mysql.tables.DwRankingProfit.DW_RANKING_PROFIT;

    /**
     * ????
     */
    public final FileStore FILE_STORE = com.jic.tnw.db.mysql.tables.FileStore.FILE_STORE;

    /**
     * ???
     */
    public final FileStoreGroup FILE_STORE_GROUP = com.jic.tnw.db.mysql.tables.FileStoreGroup.FILE_STORE_GROUP;

    /**
     * ???????
     */
    public final Log LOG = com.jic.tnw.db.mysql.tables.Log.LOG;

    /**
     * ????
     */
    public final Org ORG = com.jic.tnw.db.mysql.tables.Org.ORG;

    /**
     * ??
     */
    public final Post POST = com.jic.tnw.db.mysql.tables.Post.POST;

    /**
     * ????
     */
    public final PostGroup POST_GROUP = com.jic.tnw.db.mysql.tables.PostGroup.POST_GROUP;

    /**
     * ????
     */
    public final PostMember POST_MEMBER = com.jic.tnw.db.mysql.tables.PostMember.POST_MEMBER;

    /**
     * ???
     */
    public final Role ROLE = com.jic.tnw.db.mysql.tables.Role.ROLE;

    /**
     * ???
     */
    public final Tasks TASKS = com.jic.tnw.db.mysql.tables.Tasks.TASKS;

    /**
     * ???
     */
    public final User USER = com.jic.tnw.db.mysql.tables.User.USER;

    /**
     * ???
     */
    public final UserGroup USER_GROUP = com.jic.tnw.db.mysql.tables.UserGroup.USER_GROUP;

    /**
     * ?????
     */
    public final UserGroupMember USER_GROUP_MEMBER = com.jic.tnw.db.mysql.tables.UserGroupMember.USER_GROUP_MEMBER;

    /**
     * ????????
     */
    public final UserOrg USER_ORG = com.jic.tnw.db.mysql.tables.UserOrg.USER_ORG;

    /**
     * ?????
     */
    public final UserProfile USER_PROFILE = com.jic.tnw.db.mysql.tables.UserProfile.USER_PROFILE;

    /**
     * web_url???
     */
    public final WebUrlResource WEB_URL_RESOURCE = com.jic.tnw.db.mysql.tables.WebUrlResource.WEB_URL_RESOURCE;

    /**
     * No further instances allowed
     */
    private Tnw() {
        super("TNW", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            DwComment.DW_COMMENT,
            DwFabulous.DW_FABULOUS,
            DwMyMessage.DW_MY_MESSAGE,
            DwOldActivity.DW_OLD_ACTIVITY,
            DwOrgcircleActivity.DW_ORGCIRCLE_ACTIVITY,
            DwOrgcircleDynamic.DW_ORGCIRCLE_DYNAMIC,
            DwOtherMessage.DW_OTHER_MESSAGE,
            DwRankingCompete.DW_RANKING_COMPETE,
            DwRankingComprehensive.DW_RANKING_COMPREHENSIVE,
            DwRankingDetail.DW_RANKING_DETAIL,
            DwRankingProfit.DW_RANKING_PROFIT,
            FileStore.FILE_STORE,
            FileStoreGroup.FILE_STORE_GROUP,
            Log.LOG,
            Org.ORG,
            Post.POST,
            PostGroup.POST_GROUP,
            PostMember.POST_MEMBER,
            Role.ROLE,
            Tasks.TASKS,
            User.USER,
            UserGroup.USER_GROUP,
            UserGroupMember.USER_GROUP_MEMBER,
            UserOrg.USER_ORG,
            UserProfile.USER_PROFILE,
            WebUrlResource.WEB_URL_RESOURCE);
    }
}
