/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql;


import com.jic.tnw.db.mysql.tables.Log;
import com.jic.tnw.db.mysql.tables.Org;
import com.jic.tnw.db.mysql.tables.Post;
import com.jic.tnw.db.mysql.tables.PostGroup;
import com.jic.tnw.db.mysql.tables.PostMember;
import com.jic.tnw.db.mysql.tables.Role;
import com.jic.tnw.db.mysql.tables.Tasks;
import com.jic.tnw.db.mysql.tables.User;
import com.jic.tnw.db.mysql.tables.UserGroup;
import com.jic.tnw.db.mysql.tables.UserGroupMember;
import com.jic.tnw.db.mysql.tables.UserOrg;
import com.jic.tnw.db.mysql.tables.UserProfile;
import com.jic.tnw.db.mysql.tables.WebUrlResource;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tnw extends SchemaImpl {

    private static final long serialVersionUID = 442894412;

    /**
     * The reference instance of <code>TNW</code>
     */
    public static final Tnw TNW = new Tnw();

    /**
     * ???????
     */
    public final Log LOG = com.jic.tnw.db.mysql.tables.Log.LOG;

    /**
     * ????
     */
    public final Org ORG = com.jic.tnw.db.mysql.tables.Org.ORG;

    /**
     * ??
     */
    public final Post POST = com.jic.tnw.db.mysql.tables.Post.POST;

    /**
     * ????
     */
    public final PostGroup POST_GROUP = com.jic.tnw.db.mysql.tables.PostGroup.POST_GROUP;

    /**
     * ????
     */
    public final PostMember POST_MEMBER = com.jic.tnw.db.mysql.tables.PostMember.POST_MEMBER;

    /**
     * ???
     */
    public final Role ROLE = com.jic.tnw.db.mysql.tables.Role.ROLE;

    /**
     * ???
     */
    public final Tasks TASKS = com.jic.tnw.db.mysql.tables.Tasks.TASKS;

    /**
     * ???
     */
    public final User USER = com.jic.tnw.db.mysql.tables.User.USER;

    /**
     * ???
     */
    public final UserGroup USER_GROUP = com.jic.tnw.db.mysql.tables.UserGroup.USER_GROUP;

    /**
     * ?????
     */
    public final UserGroupMember USER_GROUP_MEMBER = com.jic.tnw.db.mysql.tables.UserGroupMember.USER_GROUP_MEMBER;

    /**
     * ????????
     */
    public final UserOrg USER_ORG = com.jic.tnw.db.mysql.tables.UserOrg.USER_ORG;

    /**
     * ?????
     */
    public final UserProfile USER_PROFILE = com.jic.tnw.db.mysql.tables.UserProfile.USER_PROFILE;

    /**
     * web_url???
     */
    public final WebUrlResource WEB_URL_RESOURCE = com.jic.tnw.db.mysql.tables.WebUrlResource.WEB_URL_RESOURCE;

    /**
     * No further instances allowed
     */
    private Tnw() {
        super("TNW", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Log.LOG,
            Org.ORG,
            Post.POST,
            PostGroup.POST_GROUP,
            PostMember.POST_MEMBER,
            Role.ROLE,
            Tasks.TASKS,
            User.USER,
            UserGroup.USER_GROUP,
            UserGroupMember.USER_GROUP_MEMBER,
            UserOrg.USER_ORG,
            UserProfile.USER_PROFILE,
            WebUrlResource.WEB_URL_RESOURCE);
    }
}
