/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables;


import com.jic.tnw.db.converter.LocalDateTimeConverter1;
import com.jic.tnw.db.mysql.Indexes;
import com.jic.tnw.db.mysql.Keys;
import com.jic.tnw.db.mysql.Tnw;
import com.jic.tnw.db.mysql.tables.records.OrgRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * ????
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Org extends TableImpl<OrgRecord> {

    private static final long serialVersionUID = -2130630683;

    /**
     * The reference instance of <code>TNW.org</code>
     */
    public static final Org ORG = new Org();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrgRecord> getRecordType() {
        return OrgRecord.class;
    }

    /**
     * The column <code>TNW.org.id</code>. ????ID
     */
    public final TableField<OrgRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "????ID");

    /**
     * The column <code>TNW.org.name</code>. ??
     */
    public final TableField<OrgRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "??");

    /**
     * The column <code>TNW.org.parent_id</code>. ?????ID
     */
    public final TableField<OrgRecord, Integer> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "?????ID");

    /**
     * The column <code>TNW.org.children_num</code>. ????????
     */
    public final TableField<OrgRecord, Integer> CHILDREN_NUM = createField("children_num", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "????????");

    /**
     * The column <code>TNW.org.depth</code>. ????????
     */
    public final TableField<OrgRecord, Integer> DEPTH = createField("depth", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "????????");

    /**
     * The column <code>TNW.org.seq</code>. ??
     */
    public final TableField<OrgRecord, Integer> SEQ = createField("seq", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "??");

    /**
     * The column <code>TNW.org.description</code>. ??
     */
    public final TableField<OrgRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "??");

    /**
     * The column <code>TNW.org.code</code>. ????
     */
    public final TableField<OrgRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "????");

    /**
     * The column <code>TNW.org.org_code</code>. ????
     */
    public final TableField<OrgRecord, String> ORG_CODE = createField("org_code", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "????");

    /**
     * The column <code>TNW.org.created_user_id</code>. ????ID
     */
    public final TableField<OrgRecord, Integer> CREATED_USER_ID = createField("created_user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "????ID");

    /**
     * The column <code>TNW.org.created_time</code>. ????
     */
    public final TableField<OrgRecord, LocalDateTime> CREATED_TIME = createField("created_time", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "????", new LocalDateTimeConverter1());

    /**
     * The column <code>TNW.org.last_upd_user_id</code>. ?????
     */
    public final TableField<OrgRecord, Integer> LAST_UPD_USER_ID = createField("last_upd_user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "?????");

    /**
     * The column <code>TNW.org.last_upd_time</code>. ??????
     */
    public final TableField<OrgRecord, LocalDateTime> LAST_UPD_TIME = createField("last_upd_time", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "??????", new LocalDateTimeConverter1());

    /**
     * The column <code>TNW.org.sync_id</code>. ????ID
     */
    public final TableField<OrgRecord, Integer> SYNC_ID = createField("sync_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "????ID");

    /**
     * Create a <code>TNW.org</code> table reference
     */
    public Org() {
        this(DSL.name("org"), null);
    }

    /**
     * Create an aliased <code>TNW.org</code> table reference
     */
    public Org(String alias) {
        this(DSL.name(alias), ORG);
    }

    /**
     * Create an aliased <code>TNW.org</code> table reference
     */
    public Org(Name alias) {
        this(alias, ORG);
    }

    private Org(Name alias, Table<OrgRecord> aliased) {
        this(alias, aliased, null);
    }

    private Org(Name alias, Table<OrgRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "????");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tnw.TNW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ORG_CODE, Indexes.ORG_ORG_CODE, Indexes.ORG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OrgRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ORG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrgRecord> getPrimaryKey() {
        return Keys.KEY_ORG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrgRecord>> getKeys() {
        return Arrays.<UniqueKey<OrgRecord>>asList(Keys.KEY_ORG_PRIMARY, Keys.KEY_ORG_CODE, Keys.KEY_ORG_ORG_CODE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Org as(String alias) {
        return new Org(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Org as(Name alias) {
        return new Org(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Org rename(String name) {
        return new Org(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Org rename(Name name) {
        return new Org(name, null);
    }
}
