/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables;


import com.jic.tnw.db.converter.LocalDateTimeConverter1;
import com.jic.tnw.db.mysql.Indexes;
import com.jic.tnw.db.mysql.Keys;
import com.jic.tnw.db.mysql.Tnw;
import com.jic.tnw.db.mysql.tables.records.PostGroupRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * ????
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostGroup extends TableImpl<PostGroupRecord> {

    private static final long serialVersionUID = -188266500;

    /**
     * The reference instance of <code>TNW.post_group</code>
     */
    public static final PostGroup POST_GROUP = new PostGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostGroupRecord> getRecordType() {
        return PostGroupRecord.class;
    }

    /**
     * The column <code>TNW.post_group.id</code>. ID
     */
    public final TableField<PostGroupRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "ID");

    /**
     * The column <code>TNW.post_group.name</code>. ??????
     */
    public final TableField<PostGroupRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "??????");

    /**
     * The column <code>TNW.post_group.seq</code>. ????
     */
    public final TableField<PostGroupRecord, Integer> SEQ = createField("seq", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "????");

    /**
     * The column <code>TNW.post_group.created_user_id</code>. ????ID
     */
    public final TableField<PostGroupRecord, Integer> CREATED_USER_ID = createField("created_user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "????ID");

    /**
     * The column <code>TNW.post_group.created_time</code>. ????
     */
    public final TableField<PostGroupRecord, LocalDateTime> CREATED_TIME = createField("created_time", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "????", new LocalDateTimeConverter1());

    /**
     * The column <code>TNW.post_group.last_upd_user_id</code>. ?????
     */
    public final TableField<PostGroupRecord, Integer> LAST_UPD_USER_ID = createField("last_upd_user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "?????");

    /**
     * The column <code>TNW.post_group.last_upd_time</code>. ??????
     */
    public final TableField<PostGroupRecord, LocalDateTime> LAST_UPD_TIME = createField("last_upd_time", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "??????", new LocalDateTimeConverter1());

    /**
     * Create a <code>TNW.post_group</code> table reference
     */
    public PostGroup() {
        this(DSL.name("post_group"), null);
    }

    /**
     * Create an aliased <code>TNW.post_group</code> table reference
     */
    public PostGroup(String alias) {
        this(DSL.name(alias), POST_GROUP);
    }

    /**
     * Create an aliased <code>TNW.post_group</code> table reference
     */
    public PostGroup(Name alias) {
        this(alias, POST_GROUP);
    }

    private PostGroup(Name alias, Table<PostGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private PostGroup(Name alias, Table<PostGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "????");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tnw.TNW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.POST_GROUP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PostGroupRecord, Integer> getIdentity() {
        return Keys.IDENTITY_POST_GROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PostGroupRecord> getPrimaryKey() {
        return Keys.KEY_POST_GROUP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PostGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<PostGroupRecord>>asList(Keys.KEY_POST_GROUP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostGroup as(String alias) {
        return new PostGroup(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostGroup as(Name alias) {
        return new PostGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PostGroup rename(String name) {
        return new PostGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PostGroup rename(Name name) {
        return new PostGroup(name, null);
    }
}
