/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.records;


import com.jic.tnw.db.mysql.tables.Log;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * ???????
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LogRecord extends UpdatableRecordImpl<LogRecord> implements Record9<Integer, Integer, String, String, String, String, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1451952705;

    /**
     * Setter for <code>TNW.log.id</code>. ????ID
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TNW.log.id</code>. ????ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TNW.log.user_id</code>. ???ID
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>TNW.log.user_id</code>. ???ID
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>TNW.log.module</code>. ??????
     */
    public void setModule(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>TNW.log.module</code>. ??????
     */
    public String getModule() {
        return (String) get(2);
    }

    /**
     * Setter for <code>TNW.log.action</code>. ????????
     */
    public void setAction(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>TNW.log.action</code>. ????????
     */
    public String getAction() {
        return (String) get(3);
    }

    /**
     * Setter for <code>TNW.log.message</code>. ????
     */
    public void setMessage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>TNW.log.message</code>. ????
     */
    public String getMessage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>TNW.log.data</code>. ????
     */
    public void setData(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>TNW.log.data</code>. ????
     */
    public String getData() {
        return (String) get(5);
    }

    /**
     * Setter for <code>TNW.log.ip</code>. ????IP
     */
    public void setIp(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>TNW.log.ip</code>. ????IP
     */
    public String getIp() {
        return (String) get(6);
    }

    /**
     * Setter for <code>TNW.log.created_time</code>. ??????
     */
    public void setCreatedTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>TNW.log.created_time</code>. ??????
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>TNW.log.level</code>. ????
     */
    public void setLevel(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>TNW.log.level</code>. ????
     */
    public String getLevel() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, String, String, String, String, String, LocalDateTime, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, String, String, String, String, String, LocalDateTime, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Log.LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Log.LOG.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Log.LOG.MODULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Log.LOG.ACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Log.LOG.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Log.LOG.DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Log.LOG.IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return Log.LOG.CREATED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Log.LOG.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getModule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getModule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value3(String value) {
        setModule(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value4(String value) {
        setAction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value5(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value6(String value) {
        setData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value7(String value) {
        setIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value8(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value9(String value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord values(Integer value1, Integer value2, String value3, String value4, String value5, String value6, String value7, LocalDateTime value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LogRecord
     */
    public LogRecord() {
        super(Log.LOG);
    }

    /**
     * Create a detached, initialised LogRecord
     */
    public LogRecord(Integer id, Integer userId, String module, String action, String message, String data, String ip, LocalDateTime createdTime, String level) {
        super(Log.LOG);

        set(0, id);
        set(1, userId);
        set(2, module);
        set(3, action);
        set(4, message);
        set(5, data);
        set(6, ip);
        set(7, createdTime);
        set(8, level);
    }
}
