/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.records;


import com.jic.tnw.db.mysql.tables.Org;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.time.LocalDateTime;


/**
 * ????
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgRecord extends UpdatableRecordImpl<OrgRecord> {

    private static final long serialVersionUID = -782449439;

    /**
     * Setter for <code>TNW.org.id</code>. ????ID
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TNW.org.id</code>. ????ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TNW.org.parent_id</code>. ?????ID
     */
    public void setParentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>TNW.org.parent_id</code>. ?????ID
     */
    public Integer getParentId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>TNW.org.children_num</code>. ????????
     */
    public void setChildrenNum(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>TNW.org.children_num</code>. ????????
     */
    public Integer getChildrenNum() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>TNW.org.depth</code>. ????????
     */
    public void setDepth(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>TNW.org.depth</code>. ????????
     */
    public Integer getDepth() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>TNW.org.seq</code>. ??
     */
    public void setSeq(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>TNW.org.seq</code>. ??
     */
    public Integer getSeq() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>TNW.org.description</code>. ??
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>TNW.org.description</code>. ??
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>TNW.org.branch_no</code>. ????
     */
    public void setBranchNo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>TNW.org.branch_no</code>. ????
     */
    public String getBranchNo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>TNW.org.org_code</code>. ????
     */
    public void setOrgCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>TNW.org.org_code</code>. ????
     */
    public String getOrgCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>TNW.org.branch_nm</code>. ????
     */
    public void setBranchNm(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>TNW.org.branch_nm</code>. ????
     */
    public String getBranchNm() {
        return (String) get(8);
    }

    /**
     * Setter for <code>TNW.org.created_user_id</code>. ????ID
     */
    public void setCreatedUserId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>TNW.org.created_user_id</code>. ????ID
     */
    public Integer getCreatedUserId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>TNW.org.created_time</code>. ????
     */
    public void setCreatedTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>TNW.org.created_time</code>. ????
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>TNW.org.last_upd_user_id</code>. ?????
     */
    public void setLastUpdUserId(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>TNW.org.last_upd_user_id</code>. ?????
     */
    public Integer getLastUpdUserId() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>TNW.org.last_upd_time</code>. ??????
     */
    public void setLastUpdTime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>TNW.org.last_upd_time</code>. ??????
     */
    public LocalDateTime getLastUpdTime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>TNW.org.sync_id</code>. ????ID
     */
    public void setSyncId(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>TNW.org.sync_id</code>. ????ID
     */
    public Integer getSyncId() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>TNW.org.tx_mt</code>. ????
     */
    public void setTxMt(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>TNW.org.tx_mt</code>. ????
     */
    public String getTxMt() {
        return (String) get(14);
    }

    /**
     * Setter for <code>TNW.org.tx_dt</code>. ????
     */
    public void setTxDt(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>TNW.org.tx_dt</code>. ????
     */
    public String getTxDt() {
        return (String) get(15);
    }

    /**
     * Setter for <code>TNW.org.branch_nm_shot</code>. ??????
     */
    public void setBranchNmShot(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>TNW.org.branch_nm_shot</code>. ??????
     */
    public String getBranchNmShot() {
        return (String) get(16);
    }

    /**
     * Setter for <code>TNW.org.branch_typ</code>. ????
     */
    public void setBranchTyp(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>TNW.org.branch_typ</code>. ????
     */
    public String getBranchTyp() {
        return (String) get(17);
    }

    /**
     * Setter for <code>TNW.org.lead_branch_no</code>. ????
     */
    public void setLeadBranchNo(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>TNW.org.lead_branch_no</code>. ????
     */
    public String getLeadBranchNo() {
        return (String) get(18);
    }

    /**
     * Setter for <code>TNW.org.address</code>. ??
     */
    public void setAddress(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>TNW.org.address</code>. ??
     */
    public String getAddress() {
        return (String) get(19);
    }

    /**
     * Setter for <code>TNW.org.longitude</code>. ??
     */
    public void setLongitude(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>TNW.org.longitude</code>. ??
     */
    public String getLongitude() {
        return (String) get(20);
    }

    /**
     * Setter for <code>TNW.org.practice_dt</code>. ????
     */
    public void setPracticeDt(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>TNW.org.practice_dt</code>. ????
     */
    public String getPracticeDt() {
        return (String) get(21);
    }

    /**
     * Setter for <code>TNW.org.business_tm</code>. ????
     */
    public void setBusinessTm(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>TNW.org.business_tm</code>. ????
     */
    public String getBusinessTm() {
        return (String) get(22);
    }

    /**
     * Setter for <code>TNW.org.decorate_dt</code>. ????
     */
    public void setDecorateDt(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>TNW.org.decorate_dt</code>. ????
     */
    public String getDecorateDt() {
        return (String) get(23);
    }

    /**
     * Setter for <code>TNW.org.branch_area</code>. ????
     */
    public void setBranchArea(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>TNW.org.branch_area</code>. ????
     */
    public String getBranchArea() {
        return (String) get(24);
    }

    /**
     * Setter for <code>TNW.org.employees_no</code>. ???
     */
    public void setEmployeesNo(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>TNW.org.employees_no</code>. ???
     */
    public String getEmployeesNo() {
        return (String) get(25);
    }

    /**
     * Setter for <code>TNW.org.parking_no</code>. ?????
     */
    public void setParkingNo(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>TNW.org.parking_no</code>. ?????
     */
    public String getParkingNo() {
        return (String) get(26);
    }

    /**
     * Setter for <code>TNW.org.self_help_equipment</code>.
     */
    public void setSelfHelpEquipment(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>TNW.org.self_help_equipment</code>.
     */
    public String getSelfHelpEquipment() {
        return (String) get(27);
    }

    /**
     * Setter for <code>TNW.org.property_rights_typ</code>. ????
     */
    public void setPropertyRightsTyp(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>TNW.org.property_rights_typ</code>. ????
     */
    public String getPropertyRightsTyp() {
        return (String) get(28);
    }

    /**
     * Setter for <code>TNW.org.business_typ</code>. ????
     */
    public void setBusinessTyp(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>TNW.org.business_typ</code>. ????
     */
    public String getBusinessTyp() {
        return (String) get(29);
    }

    /**
     * Setter for <code>TNW.org.electronic_equipment</code>. ????
     */
    public void setElectronicEquipment(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>TNW.org.electronic_equipment</code>. ????
     */
    public String getElectronicEquipment() {
        return (String) get(30);
    }

    /**
     * Setter for <code>TNW.org.tel_no</code>. ????
     */
    public void setTelNo(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>TNW.org.tel_no</code>. ????
     */
    public String getTelNo() {
        return (String) get(31);
    }

    /**
     * Setter for <code>TNW.org.branch_lead</code>. ?????
     */
    public void setBranchLead(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>TNW.org.branch_lead</code>. ?????
     */
    public String getBranchLead() {
        return (String) get(32);
    }

    /**
     * Setter for <code>TNW.org.yitiji</code>. ???
     */
    public void setYitiji(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>TNW.org.yitiji</code>. ???
     */
    public String getYitiji() {
        return (String) get(33);
    }

    /**
     * Setter for <code>TNW.org.qukuanji</code>. ???
     */
    public void setQukuanji(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>TNW.org.qukuanji</code>. ???
     */
    public String getQukuanji() {
        return (String) get(34);
    }

    /**
     * Setter for <code>TNW.org.branch_pic</code>. ??
     */
    public void setBranchPic(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>TNW.org.branch_pic</code>. ??
     */
    public String getBranchPic() {
        return (String) get(35);
    }

    /**
     * Setter for <code>TNW.org.branch_special</code>. ????
     */
    public void setBranchSpecial(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>TNW.org.branch_special</code>. ????
     */
    public String getBranchSpecial() {
        return (String) get(36);
    }

    /**
     * Setter for <code>TNW.org.enabled</code>.
     */
    public void setEnabled(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>TNW.org.enabled</code>.
     */
    public String getEnabled() {
        return (String) get(37);
    }

    /**
     * Setter for <code>TNW.org.increacenum</code>.
     */
    public void setIncreacenum(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>TNW.org.increacenum</code>.
     */
    public String getIncreacenum() {
        return (String) get(38);
    }

    /**
     * Setter for <code>TNW.org.branch_typ1</code>.
     */
    public void setBranchTyp1(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>TNW.org.branch_typ1</code>.
     */
    public String getBranchTyp1() {
        return (String) get(39);
    }

    /**
     * Setter for <code>TNW.org.area_typ</code>. ??
     */
    public void setAreaTyp(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>TNW.org.area_typ</code>. ??
     */
    public String getAreaTyp() {
        return (String) get(40);
    }

    /**
     * Setter for <code>TNW.org.temporarily</code>.
     */
    public void setTemporarily(String value) {
        set(41, value);
    }

    /**
     * Getter for <code>TNW.org.temporarily</code>.
     */
    public String getTemporarily() {
        return (String) get(41);
    }

    /**
     * Setter for <code>TNW.org.dmeg</code>.
     */
    public void setDmeg(String value) {
        set(42, value);
    }

    /**
     * Getter for <code>TNW.org.dmeg</code>.
     */
    public String getDmeg() {
        return (String) get(42);
    }

    /**
     * Setter for <code>TNW.org.branch_lead_no</code>. ???????
     */
    public void setBranchLeadNo(String value) {
        set(43, value);
    }

    /**
     * Getter for <code>TNW.org.branch_lead_no</code>. ???????
     */
    public String getBranchLeadNo() {
        return (String) get(43);
    }

    /**
     * Setter for <code>TNW.org.flag</code>. ?????????C,4 |Y,1|Z,3|??Y,2 ?
     */
    public void setFlag(String value) {
        set(44, value);
    }

    /**
     * Getter for <code>TNW.org.flag</code>. ?????????C,4 |Y,1|Z,3|??Y,2 ?
     */
    public String getFlag() {
        return (String) get(44);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrgRecord
     */
    public OrgRecord() {
        super(Org.ORG);
    }

    /**
     * Create a detached, initialised OrgRecord
     */
    public OrgRecord(Integer id, Integer parentId, Integer childrenNum, Integer depth, Integer seq, String description, String branchNo, String orgCode, String branchNm, Integer createdUserId, LocalDateTime createdTime, Integer lastUpdUserId, LocalDateTime lastUpdTime, Integer syncId, String txMt, String txDt, String branchNmShot, String branchTyp, String leadBranchNo, String address, String longitude, String practiceDt, String businessTm, String decorateDt, String branchArea, String employeesNo, String parkingNo, String selfHelpEquipment, String propertyRightsTyp, String businessTyp, String electronicEquipment, String telNo, String branchLead, String yitiji, String qukuanji, String branchPic, String branchSpecial, String enabled, String increacenum, String branchTyp1, String areaTyp, String temporarily, String dmeg, String branchLeadNo, String flag) {
        super(Org.ORG);

        set(0, id);
        set(1, parentId);
        set(2, childrenNum);
        set(3, depth);
        set(4, seq);
        set(5, description);
        set(6, branchNo);
        set(7, orgCode);
        set(8, branchNm);
        set(9, createdUserId);
        set(10, createdTime);
        set(11, lastUpdUserId);
        set(12, lastUpdTime);
        set(13, syncId);
        set(14, txMt);
        set(15, txDt);
        set(16, branchNmShot);
        set(17, branchTyp);
        set(18, leadBranchNo);
        set(19, address);
        set(20, longitude);
        set(21, practiceDt);
        set(22, businessTm);
        set(23, decorateDt);
        set(24, branchArea);
        set(25, employeesNo);
        set(26, parkingNo);
        set(27, selfHelpEquipment);
        set(28, propertyRightsTyp);
        set(29, businessTyp);
        set(30, electronicEquipment);
        set(31, telNo);
        set(32, branchLead);
        set(33, yitiji);
        set(34, qukuanji);
        set(35, branchPic);
        set(36, branchSpecial);
        set(37, enabled);
        set(38, increacenum);
        set(39, branchTyp1);
        set(40, areaTyp);
        set(41, temporarily);
        set(42, dmeg);
        set(43, branchLeadNo);
        set(44, flag);
    }
}
