/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.records;


import com.jic.tnw.db.mysql.tables.Post;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * ??
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostRecord extends UpdatableRecordImpl<PostRecord> implements Record9<Integer, String, Integer, Integer, String, Integer, LocalDateTime, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1099185365;

    /**
     * Setter for <code>TNW.post.id</code>. ID
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TNW.post.id</code>. ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TNW.post.name</code>. ????
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>TNW.post.name</code>. ????
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TNW.post.group_id</code>. ??ID
     */
    public void setGroupId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>TNW.post.group_id</code>. ??ID
     */
    public Integer getGroupId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>TNW.post.seq</code>. ????
     */
    public void setSeq(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>TNW.post.seq</code>. ????
     */
    public Integer getSeq() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>TNW.post.code</code>. ????
     */
    public void setCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>TNW.post.code</code>. ????
     */
    public String getCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>TNW.post.created_user_id</code>. ????ID
     */
    public void setCreatedUserId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>TNW.post.created_user_id</code>. ????ID
     */
    public Integer getCreatedUserId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>TNW.post.created_time</code>. ????
     */
    public void setCreatedTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>TNW.post.created_time</code>. ????
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>TNW.post.last_upd_user_id</code>. ?????
     */
    public void setLastUpdUserId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>TNW.post.last_upd_user_id</code>. ?????
     */
    public Integer getLastUpdUserId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>TNW.post.last_upd_time</code>. ??????
     */
    public void setLastUpdTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>TNW.post.last_upd_time</code>. ??????
     */
    public LocalDateTime getLastUpdTime() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, Integer, String, Integer, LocalDateTime, Integer, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, Integer, String, Integer, LocalDateTime, Integer, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Post.POST.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Post.POST.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Post.POST.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Post.POST.SEQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Post.POST.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Post.POST.CREATED_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return Post.POST.CREATED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Post.POST.LAST_UPD_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field9() {
        return Post.POST.LAST_UPD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getSeq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getCreatedUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getLastUpdUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component9() {
        return getLastUpdTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getSeq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getCreatedUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getLastUpdUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value9() {
        return getLastUpdTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value3(Integer value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value4(Integer value) {
        setSeq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value5(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value6(Integer value) {
        setCreatedUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value7(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value8(Integer value) {
        setLastUpdUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value9(LocalDateTime value) {
        setLastUpdTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord values(Integer value1, String value2, Integer value3, Integer value4, String value5, Integer value6, LocalDateTime value7, Integer value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostRecord
     */
    public PostRecord() {
        super(Post.POST);
    }

    /**
     * Create a detached, initialised PostRecord
     */
    public PostRecord(Integer id, String name, Integer groupId, Integer seq, String code, Integer createdUserId, LocalDateTime createdTime, Integer lastUpdUserId, LocalDateTime lastUpdTime) {
        super(Post.POST);

        set(0, id);
        set(1, name);
        set(2, groupId);
        set(3, seq);
        set(4, code);
        set(5, createdUserId);
        set(6, createdTime);
        set(7, lastUpdUserId);
        set(8, lastUpdTime);
    }
}
