/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.records;


import com.jic.tnw.db.mysql.enums.TasksStatus;
import com.jic.tnw.db.mysql.tables.Tasks;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * ???
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TasksRecord extends UpdatableRecordImpl<TasksRecord> implements Record8<Integer, String, LocalDateTime, LocalDateTime, Long, String, TasksStatus, String> {

    private static final long serialVersionUID = -2107522762;

    /**
     * Setter for <code>TNW.tasks.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TNW.tasks.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TNW.tasks.name</code>. ????
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>TNW.tasks.name</code>. ????
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TNW.tasks.begin_time</code>. ????
     */
    public void setBeginTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>TNW.tasks.begin_time</code>. ????
     */
    public LocalDateTime getBeginTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>TNW.tasks.end_time</code>. ????
     */
    public void setEndTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>TNW.tasks.end_time</code>. ????
     */
    public LocalDateTime getEndTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>TNW.tasks.elapsed</code>. ????,??:??
     */
    public void setElapsed(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>TNW.tasks.elapsed</code>. ????,??:??
     */
    public Long getElapsed() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>TNW.tasks.trigged_user_name</code>. ???????(??????:scheduled)
     */
    public void setTriggedUserName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>TNW.tasks.trigged_user_name</code>. ???????(??????:scheduled)
     */
    public String getTriggedUserName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>TNW.tasks.status</code>. ????
     */
    public void setStatus(TasksStatus value) {
        set(6, value);
    }

    /**
     * Getter for <code>TNW.tasks.status</code>. ????
     */
    public TasksStatus getStatus() {
        return (TasksStatus) get(6);
    }

    /**
     * Setter for <code>TNW.tasks.result</code>. ????(json??)
     */
    public void setResult(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>TNW.tasks.result</code>. ????(json??)
     */
    public String getResult() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, LocalDateTime, LocalDateTime, Long, String, TasksStatus, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, LocalDateTime, LocalDateTime, Long, String, TasksStatus, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Tasks.TASKS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tasks.TASKS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field3() {
        return Tasks.TASKS.BEGIN_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return Tasks.TASKS.END_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Tasks.TASKS.ELAPSED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Tasks.TASKS.TRIGGED_USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<TasksStatus> field7() {
        return Tasks.TASKS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Tasks.TASKS.RESULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component3() {
        return getBeginTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getElapsed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTriggedUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksStatus component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value3() {
        return getBeginTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getElapsed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTriggedUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksStatus value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksRecord value3(LocalDateTime value) {
        setBeginTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksRecord value4(LocalDateTime value) {
        setEndTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksRecord value5(Long value) {
        setElapsed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksRecord value6(String value) {
        setTriggedUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksRecord value7(TasksStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksRecord value8(String value) {
        setResult(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksRecord values(Integer value1, String value2, LocalDateTime value3, LocalDateTime value4, Long value5, String value6, TasksStatus value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TasksRecord
     */
    public TasksRecord() {
        super(Tasks.TASKS);
    }

    /**
     * Create a detached, initialised TasksRecord
     */
    public TasksRecord(Integer id, String name, LocalDateTime beginTime, LocalDateTime endTime, Long elapsed, String triggedUserName, TasksStatus status, String result) {
        super(Tasks.TASKS);

        set(0, id);
        set(1, name);
        set(2, beginTime);
        set(3, endTime);
        set(4, elapsed);
        set(5, triggedUserName);
        set(6, status);
        set(7, result);
    }
}
