/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.records;


import com.jic.tnw.db.mysql.enums.UserProfileGender;
import com.jic.tnw.db.mysql.tables.UserProfile;

import java.sql.Date;
import java.time.LocalDate;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * ?????
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserProfileRecord extends UpdatableRecordImpl<UserProfileRecord> {

    private static final long serialVersionUID = -1026070334;

    /**
     * Setter for <code>TNW.user_profile.id</code>. ??ID
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TNW.user_profile.id</code>. ??ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TNW.user_profile.idcard</code>. ?????
     */
    public void setIdcard(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>TNW.user_profile.idcard</code>. ?????
     */
    public String getIdcard() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TNW.user_profile.gender</code>. ??
     */
    public void setGender(UserProfileGender value) {
        set(2, value);
    }

    /**
     * Getter for <code>TNW.user_profile.gender</code>. ??
     */
    public UserProfileGender getGender() {
        return (UserProfileGender) get(2);
    }

    /**
     * Setter for <code>TNW.user_profile.iam</code>. ???
     */
    public void setIam(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>TNW.user_profile.iam</code>. ???
     */
    public String getIam() {
        return (String) get(3);
    }

    /**
     * Setter for <code>TNW.user_profile.birthday</code>. ??
     */
    public void setBirthday(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>TNW.user_profile.birthday</code>. ??
     */
    public Date getBirthday() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>TNW.user_profile.city</code>. ??
     */
    public void setCity(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>TNW.user_profile.city</code>. ??
     */
    public String getCity() {
        return (String) get(5);
    }

    /**
     * Setter for <code>TNW.user_profile.qq</code>. QQ
     */
    public void setQq(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>TNW.user_profile.qq</code>. QQ
     */
    public String getQq() {
        return (String) get(6);
    }

    /**
     * Setter for <code>TNW.user_profile.signature</code>. ??
     */
    public void setSignature(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>TNW.user_profile.signature</code>. ??
     */
    public String getSignature() {
        return (String) get(7);
    }

    /**
     * Setter for <code>TNW.user_profile.about</code>. ????
     */
    public void setAbout(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>TNW.user_profile.about</code>. ????
     */
    public String getAbout() {
        return (String) get(8);
    }

    /**
     * Setter for <code>TNW.user_profile.company</code>. ??
     */
    public void setCompany(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>TNW.user_profile.company</code>. ??
     */
    public String getCompany() {
        return (String) get(9);
    }

    /**
     * Setter for <code>TNW.user_profile.job</code>. ??
     */
    public void setJob(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>TNW.user_profile.job</code>. ??
     */
    public String getJob() {
        return (String) get(10);
    }

    /**
     * Setter for <code>TNW.user_profile.school</code>. ??
     */
    public void setSchool(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>TNW.user_profile.school</code>. ??
     */
    public String getSchool() {
        return (String) get(11);
    }

    /**
     * Setter for <code>TNW.user_profile.class</code>. ??
     */
    public void setClass_(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>TNW.user_profile.class</code>. ??
     */
    public String getClass_() {
        return (String) get(12);
    }

    /**
     * Setter for <code>TNW.user_profile.weibo</code>. ??
     */
    public void setWeibo(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>TNW.user_profile.weibo</code>. ??
     */
    public String getWeibo() {
        return (String) get(13);
    }

    /**
     * Setter for <code>TNW.user_profile.weixin</code>. ??
     */
    public void setWeixin(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>TNW.user_profile.weixin</code>. ??
     */
    public String getWeixin() {
        return (String) get(14);
    }

    /**
     * Setter for <code>TNW.user_profile.is_QQ_Public</code>. QQ?????
     */
    public void setIsQqPublic(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>TNW.user_profile.is_QQ_Public</code>. QQ?????
     */
    public Integer getIsQqPublic() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>TNW.user_profile.is_Weixin_Public</code>. ??????
     */
    public void setIsWeixinPublic(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>TNW.user_profile.is_Weixin_Public</code>. ??????
     */
    public Integer getIsWeixinPublic() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>TNW.user_profile.is_Weibo_Public</code>. ??????
     */
    public void setIsWeiboPublic(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>TNW.user_profile.is_Weibo_Public</code>. ??????
     */
    public Integer getIsWeiboPublic() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>TNW.user_profile.site</code>. ??
     */
    public void setSite(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>TNW.user_profile.site</code>. ??
     */
    public String getSite() {
        return (String) get(18);
    }

    /**
     * Setter for <code>TNW.user_profile.field1_int</code>.
     */
    public void setField1Int(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>TNW.user_profile.field1_int</code>.
     */
    public Integer getField1Int() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>TNW.user_profile.field2_int</code>.
     */
    public void setField2Int(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>TNW.user_profile.field2_int</code>.
     */
    public Integer getField2Int() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>TNW.user_profile.field3_int</code>.
     */
    public void setField3Int(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>TNW.user_profile.field3_int</code>.
     */
    public Integer getField3Int() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>TNW.user_profile.field4_int</code>.
     */
    public void setField4Int(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>TNW.user_profile.field4_int</code>.
     */
    public Integer getField4Int() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>TNW.user_profile.field5_int</code>.
     */
    public void setField5Int(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>TNW.user_profile.field5_int</code>.
     */
    public Integer getField5Int() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>TNW.user_profile.field1_date</code>.
     */
    public void setField1Date(LocalDate value) {
        set(24, value);
    }

    /**
     * Getter for <code>TNW.user_profile.field1_date</code>.
     */
    public LocalDate getField1Date() {
        return (LocalDate) get(24);
    }

    /**
     * Setter for <code>TNW.user_profile.field2_date</code>.
     */
    public void setField2Date(LocalDate value) {
        set(25, value);
    }

    /**
     * Getter for <code>TNW.user_profile.field2_date</code>.
     */
    public LocalDate getField2Date() {
        return (LocalDate) get(25);
    }

    /**
     * Setter for <code>TNW.user_profile.field3_date</code>.
     */
    public void setField3Date(LocalDate value) {
        set(26, value);
    }

    /**
     * Getter for <code>TNW.user_profile.field3_date</code>.
     */
    public LocalDate getField3Date() {
        return (LocalDate) get(26);
    }

    /**
     * Setter for <code>TNW.user_profile.field4_date</code>.
     */
    public void setField4Date(LocalDate value) {
        set(27, value);
    }

    /**
     * Getter for <code>TNW.user_profile.field4_date</code>.
     */
    public LocalDate getField4Date() {
        return (LocalDate) get(27);
    }

    /**
     * Setter for <code>TNW.user_profile.field5_date</code>.
     */
    public void setField5Date(LocalDate value) {
        set(28, value);
    }

    /**
     * Getter for <code>TNW.user_profile.field5_date</code>.
     */
    public LocalDate getField5Date() {
        return (LocalDate) get(28);
    }

    /**
     * Setter for <code>TNW.user_profile.field1_float</code>.
     */
    public void setField1Float(Double value) {
        set(29, value);
    }

    /**
     * Getter for <code>TNW.user_profile.field1_float</code>.
     */
    public Double getField1Float() {
        return (Double) get(29);
    }

    /**
     * Setter for <code>TNW.user_profile.field2_float</code>.
     */
    public void setField2Float(Double value) {
        set(30, value);
    }

    /**
     * Getter for <code>TNW.user_profile.field2_float</code>.
     */
    public Double getField2Float() {
        return (Double) get(30);
    }

    /**
     * Setter for <code>TNW.user_profile.field3_float</code>.
     */
    public void setField3Float(Double value) {
        set(31, value);
    }

    /**
     * Getter for <code>TNW.user_profile.field3_float</code>.
     */
    public Double getField3Float() {
        return (Double) get(31);
    }

    /**
     * Setter for <code>TNW.user_profile.field4_float</code>.
     */
    public void setField4Float(Double value) {
        set(32, value);
    }

    /**
     * Getter for <code>TNW.user_profile.field4_float</code>.
     */
    public Double getField4Float() {
        return (Double) get(32);
    }

    /**
     * Setter for <code>TNW.user_profile.field5_float</code>.
     */
    public void setField5Float(Double value) {
        set(33, value);
    }

    /**
     * Getter for <code>TNW.user_profile.field5_float</code>.
     */
    public Double getField5Float() {
        return (Double) get(33);
    }

    /**
     * Setter for <code>TNW.user_profile.Field1_varchar</code>.
     */
    public void setField1Varchar(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field1_varchar</code>.
     */
    public String getField1Varchar() {
        return (String) get(34);
    }

    /**
     * Setter for <code>TNW.user_profile.Field2_varchar</code>.
     */
    public void setField2Varchar(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field2_varchar</code>.
     */
    public String getField2Varchar() {
        return (String) get(35);
    }

    /**
     * Setter for <code>TNW.user_profile.Field3_varchar</code>.
     */
    public void setField3Varchar(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field3_varchar</code>.
     */
    public String getField3Varchar() {
        return (String) get(36);
    }

    /**
     * Setter for <code>TNW.user_profile.Field4_varchar</code>.
     */
    public void setField4Varchar(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field4_varchar</code>.
     */
    public String getField4Varchar() {
        return (String) get(37);
    }

    /**
     * Setter for <code>TNW.user_profile.Field5_varchar</code>.
     */
    public void setField5Varchar(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field5_varchar</code>.
     */
    public String getField5Varchar() {
        return (String) get(38);
    }

    /**
     * Setter for <code>TNW.user_profile.Field6_varchar</code>.
     */
    public void setField6Varchar(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field6_varchar</code>.
     */
    public String getField6Varchar() {
        return (String) get(39);
    }

    /**
     * Setter for <code>TNW.user_profile.Field7_varchar</code>.
     */
    public void setField7Varchar(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field7_varchar</code>.
     */
    public String getField7Varchar() {
        return (String) get(40);
    }

    /**
     * Setter for <code>TNW.user_profile.Field8_varchar</code>.
     */
    public void setField8Varchar(String value) {
        set(41, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field8_varchar</code>.
     */
    public String getField8Varchar() {
        return (String) get(41);
    }

    /**
     * Setter for <code>TNW.user_profile.Field9_varchar</code>.
     */
    public void setField9Varchar(String value) {
        set(42, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field9_varchar</code>.
     */
    public String getField9Varchar() {
        return (String) get(42);
    }

    /**
     * Setter for <code>TNW.user_profile.Field10_varchar</code>.
     */
    public void setField10Varchar(String value) {
        set(43, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field10_varchar</code>.
     */
    public String getField10Varchar() {
        return (String) get(43);
    }

    /**
     * Setter for <code>TNW.user_profile.Field1_text</code>.
     */
    public void setField1Text(String value) {
        set(44, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field1_text</code>.
     */
    public String getField1Text() {
        return (String) get(44);
    }

    /**
     * Setter for <code>TNW.user_profile.Field2_text</code>.
     */
    public void setField2Text(String value) {
        set(45, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field2_text</code>.
     */
    public String getField2Text() {
        return (String) get(45);
    }

    /**
     * Setter for <code>TNW.user_profile.Field3_text</code>.
     */
    public void setField3Text(String value) {
        set(46, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field3_text</code>.
     */
    public String getField3Text() {
        return (String) get(46);
    }

    /**
     * Setter for <code>TNW.user_profile.Field4_text</code>.
     */
    public void setField4Text(String value) {
        set(47, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field4_text</code>.
     */
    public String getField4Text() {
        return (String) get(47);
    }

    /**
     * Setter for <code>TNW.user_profile.Field5_text</code>.
     */
    public void setField5Text(String value) {
        set(48, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field5_text</code>.
     */
    public String getField5Text() {
        return (String) get(48);
    }

    /**
     * Setter for <code>TNW.user_profile.Field6_text</code>.
     */
    public void setField6Text(String value) {
        set(49, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field6_text</code>.
     */
    public String getField6Text() {
        return (String) get(49);
    }

    /**
     * Setter for <code>TNW.user_profile.Field7_text</code>.
     */
    public void setField7Text(String value) {
        set(50, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field7_text</code>.
     */
    public String getField7Text() {
        return (String) get(50);
    }

    /**
     * Setter for <code>TNW.user_profile.Field8_text</code>.
     */
    public void setField8Text(String value) {
        set(51, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field8_text</code>.
     */
    public String getField8Text() {
        return (String) get(51);
    }

    /**
     * Setter for <code>TNW.user_profile.Field9_text</code>.
     */
    public void setField9Text(String value) {
        set(52, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field9_text</code>.
     */
    public String getField9Text() {
        return (String) get(52);
    }

    /**
     * Setter for <code>TNW.user_profile.Field10_text</code>.
     */
    public void setField10Text(String value) {
        set(53, value);
    }

    /**
     * Getter for <code>TNW.user_profile.Field10_text</code>.
     */
    public String getField10Text() {
        return (String) get(53);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserProfileRecord
     */
    public UserProfileRecord() {
        super(UserProfile.USER_PROFILE);
    }

    /**
     * Create a detached, initialised UserProfileRecord
     */
    public UserProfileRecord(Integer id, String idcard, UserProfileGender gender, String iam, Date birthday, String city, String qq, String signature, String about, String company, String job, String school, String class_, String weibo, String weixin, Integer isQqPublic, Integer isWeixinPublic, Integer isWeiboPublic, String site, Integer field1Int, Integer field2Int, Integer field3Int, Integer field4Int, Integer field5Int, LocalDate field1Date, LocalDate field2Date, LocalDate field3Date, LocalDate field4Date, LocalDate field5Date, Double field1Float, Double field2Float, Double field3Float, Double field4Float, Double field5Float, String field1Varchar, String field2Varchar, String field3Varchar, String field4Varchar, String field5Varchar, String field6Varchar, String field7Varchar, String field8Varchar, String field9Varchar, String field10Varchar, String field1Text, String field2Text, String field3Text, String field4Text, String field5Text, String field6Text, String field7Text, String field8Text, String field9Text, String field10Text) {
        super(UserProfile.USER_PROFILE);

        set(0, id);
        set(1, idcard);
        set(2, gender);
        set(3, iam);
        set(4, birthday);
        set(5, city);
        set(6, qq);
        set(7, signature);
        set(8, about);
        set(9, company);
        set(10, job);
        set(11, school);
        set(12, class_);
        set(13, weibo);
        set(14, weixin);
        set(15, isQqPublic);
        set(16, isWeixinPublic);
        set(17, isWeiboPublic);
        set(18, site);
        set(19, field1Int);
        set(20, field2Int);
        set(21, field3Int);
        set(22, field4Int);
        set(23, field5Int);
        set(24, field1Date);
        set(25, field2Date);
        set(26, field3Date);
        set(27, field4Date);
        set(28, field5Date);
        set(29, field1Float);
        set(30, field2Float);
        set(31, field3Float);
        set(32, field4Float);
        set(33, field5Float);
        set(34, field1Varchar);
        set(35, field2Varchar);
        set(36, field3Varchar);
        set(37, field4Varchar);
        set(38, field5Varchar);
        set(39, field6Varchar);
        set(40, field7Varchar);
        set(41, field8Varchar);
        set(42, field9Varchar);
        set(43, field10Varchar);
        set(44, field1Text);
        set(45, field2Text);
        set(46, field3Text);
        set(47, field4Text);
        set(48, field5Text);
        set(49, field6Text);
        set(50, field7Text);
        set(51, field8Text);
        set(52, field9Text);
        set(53, field10Text);
    }
}
