/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.records;


import com.jic.tnw.db.mysql.tables.UserGroupMember;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * ?????
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupMemberRecord extends UpdatableRecordImpl<UserGroupMemberRecord> implements Record8<Integer, Integer, Integer, String, Integer, LocalDateTime, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1433627225;

    /**
     * Setter for <code>TNW.user_group_member.id</code>. ID
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TNW.user_group_member.id</code>. ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TNW.user_group_member.group_id</code>. ???ID
     */
    public void setGroupId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>TNW.user_group_member.group_id</code>. ???ID
     */
    public Integer getGroupId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>TNW.user_group_member.member_id</code>. ????ID
     */
    public void setMemberId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>TNW.user_group_member.member_id</code>. ????ID
     */
    public Integer getMemberId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>TNW.user_group_member.member_type</code>. ????
     */
    public void setMemberType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>TNW.user_group_member.member_type</code>. ????
     */
    public String getMemberType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>TNW.user_group_member.created_user_id</code>. ????ID
     */
    public void setCreatedUserId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>TNW.user_group_member.created_user_id</code>. ????ID
     */
    public Integer getCreatedUserId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>TNW.user_group_member.created_time</code>. ????
     */
    public void setCreatedTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>TNW.user_group_member.created_time</code>. ????
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>TNW.user_group_member.last_upd_user_id</code>. ?????
     */
    public void setLastUpdUserId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>TNW.user_group_member.last_upd_user_id</code>. ?????
     */
    public Integer getLastUpdUserId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>TNW.user_group_member.last_upd_time</code>. ??????
     */
    public void setLastUpdTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>TNW.user_group_member.last_upd_time</code>. ??????
     */
    public LocalDateTime getLastUpdTime() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, String, Integer, LocalDateTime, Integer, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, String, Integer, LocalDateTime, Integer, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserGroupMember.USER_GROUP_MEMBER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserGroupMember.USER_GROUP_MEMBER.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserGroupMember.USER_GROUP_MEMBER.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserGroupMember.USER_GROUP_MEMBER.MEMBER_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return UserGroupMember.USER_GROUP_MEMBER.CREATED_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return UserGroupMember.USER_GROUP_MEMBER.CREATED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return UserGroupMember.USER_GROUP_MEMBER.LAST_UPD_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return UserGroupMember.USER_GROUP_MEMBER.LAST_UPD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMemberType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getCreatedUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getLastUpdUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getLastUpdTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMemberType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getCreatedUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getLastUpdUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getLastUpdTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupMemberRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupMemberRecord value2(Integer value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupMemberRecord value3(Integer value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupMemberRecord value4(String value) {
        setMemberType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupMemberRecord value5(Integer value) {
        setCreatedUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupMemberRecord value6(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupMemberRecord value7(Integer value) {
        setLastUpdUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupMemberRecord value8(LocalDateTime value) {
        setLastUpdTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupMemberRecord values(Integer value1, Integer value2, Integer value3, String value4, Integer value5, LocalDateTime value6, Integer value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserGroupMemberRecord
     */
    public UserGroupMemberRecord() {
        super(UserGroupMember.USER_GROUP_MEMBER);
    }

    /**
     * Create a detached, initialised UserGroupMemberRecord
     */
    public UserGroupMemberRecord(Integer id, Integer groupId, Integer memberId, String memberType, Integer createdUserId, LocalDateTime createdTime, Integer lastUpdUserId, LocalDateTime lastUpdTime) {
        super(UserGroupMember.USER_GROUP_MEMBER);

        set(0, id);
        set(1, groupId);
        set(2, memberId);
        set(3, memberType);
        set(4, createdUserId);
        set(5, createdTime);
        set(6, lastUpdUserId);
        set(7, lastUpdTime);
    }
}
