/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.records;


import com.jic.tnw.db.mysql.enums.UserApprovalStatus;
import com.jic.tnw.db.mysql.tables.User;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.time.LocalDateTime;


/**
 * ???
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> {

    private static final long serialVersionUID = -1967136277;

    /**
     * Setter for <code>TNW.user.luuserid</code>. ??ID--??
     */
    public void setLuuserid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>TNW.user.luuserid</code>. ??ID--??
     */
    public String getLuuserid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>TNW.user.luusername</code>. ???
     */
    public void setLuusername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>TNW.user.luusername</code>. ???
     */
    public String getLuusername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TNW.user.luemail</code>. ????
     */
    public void setLuemail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>TNW.user.luemail</code>. ????
     */
    public String getLuemail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>TNW.user.lupwd</code>. ????
     */
    public void setLupwd(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>TNW.user.lupwd</code>. ????
     */
    public String getLupwd() {
        return (String) get(3);
    }

    /**
     * Setter for <code>TNW.user.luoldpwd</code>. old??
     */
    public void setLuoldpwd(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>TNW.user.luoldpwd</code>. old??
     */
    public String getLuoldpwd() {
        return (String) get(4);
    }

    /**
     * Setter for <code>TNW.user.lumobile</code>. ??
     */
    public void setLumobile(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>TNW.user.lumobile</code>. ??
     */
    public String getLumobile() {
        return (String) get(5);
    }

    /**
     * Setter for <code>TNW.user.luphone</code>. ??
     */
    public void setLuphone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>TNW.user.luphone</code>. ??
     */
    public String getLuphone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>TNW.user.luworkercode</code>. ???
     */
    public void setLuworkercode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>TNW.user.luworkercode</code>. ???
     */
    public String getLuworkercode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>TNW.user.luusertype</code>. ????
     */
    public void setLuusertype(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>TNW.user.luusertype</code>. ????
     */
    public String getLuusertype() {
        return (String) get(8);
    }

    /**
     * Setter for <code>TNW.user.luregtime</code>. ????
     */
    public void setLuregtime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>TNW.user.luregtime</code>. ????
     */
    public LocalDateTime getLuregtime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>TNW.user.lulastlogtime</code>. ??????
     */
    public void setLulastlogtime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>TNW.user.lulastlogtime</code>. ??????
     */
    public LocalDateTime getLulastlogtime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>TNW.user.lulastlogip</code>. ????IP
     */
    public void setLulastlogip(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>TNW.user.lulastlogip</code>. ????IP
     */
    public String getLulastlogip() {
        return (String) get(11);
    }

    /**
     * Setter for <code>TNW.user.luheadpic</code>. ??
     */
    public void setLuheadpic(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>TNW.user.luheadpic</code>. ??
     */
    public String getLuheadpic() {
        return (String) get(12);
    }

    /**
     * Setter for <code>TNW.user.position_id</code>. ??id
     */
    public void setPositionId(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>TNW.user.position_id</code>. ??id
     */
    public String getPositionId() {
        return (String) get(13);
    }

    /**
     * Setter for <code>TNW.user.position_name</code>. ????
     */
    public void setPositionName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>TNW.user.position_name</code>. ????
     */
    public String getPositionName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>TNW.user.branch_no</code>. ???
     */
    public void setBranchNo(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>TNW.user.branch_no</code>. ???
     */
    public String getBranchNo() {
        return (String) get(15);
    }

    /**
     * Setter for <code>TNW.user.branch_nm</code>. ????
     */
    public void setBranchNm(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>TNW.user.branch_nm</code>. ????
     */
    public String getBranchNm() {
        return (String) get(16);
    }

    /**
     * Setter for <code>TNW.user.pointpraise_no</code>. ???
     */
    public void setPointpraiseNo(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>TNW.user.pointpraise_no</code>. ???
     */
    public String getPointpraiseNo() {
        return (String) get(17);
    }

    /**
     * Setter for <code>TNW.user.message_no</code>. ???
     */
    public void setMessageNo(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>TNW.user.message_no</code>. ???
     */
    public String getMessageNo() {
        return (String) get(18);
    }

    /**
     * Setter for <code>TNW.user.comment_no</code>. ???
     */
    public void setCommentNo(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>TNW.user.comment_no</code>. ???
     */
    public String getCommentNo() {
        return (String) get(19);
    }

    /**
     * Setter for <code>TNW.user.lubrowsertype</code>.
     */
    public void setLubrowsertype(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>TNW.user.lubrowsertype</code>.
     */
    public String getLubrowsertype() {
        return (String) get(20);
    }

    /**
     * Setter for <code>TNW.user.luflag</code>. ??
     */
    public void setLuflag(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>TNW.user.luflag</code>. ??
     */
    public String getLuflag() {
        return (String) get(21);
    }

    /**
     * Setter for <code>TNW.user.luactive</code>. ?????
     */
    public void setLuactive(Boolean value) {
        set(22, value);
    }

    /**
     * Getter for <code>TNW.user.luactive</code>. ?????
     */
    public Boolean getLuactive() {
        return (Boolean) get(22);
    }

    /**
     * Setter for <code>TNW.user.lusex</code>. ??
     */
    public void setLusex(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>TNW.user.lusex</code>. ??
     */
    public String getLusex() {
        return (String) get(23);
    }

    /**
     * Setter for <code>TNW.user.lulogintoken</code>. ??token
     */
    public void setLulogintoken(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>TNW.user.lulogintoken</code>. ??token
     */
    public String getLulogintoken() {
        return (String) get(24);
    }

    /**
     * Setter for <code>TNW.user.token</code>. token
     */
    public void setToken(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>TNW.user.token</code>. token
     */
    public String getToken() {
        return (String) get(25);
    }

    /**
     * Setter for <code>TNW.user.luenabled</code>. ??
     */
    public void setLuenabled(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>TNW.user.luenabled</code>. ??
     */
    public String getLuenabled() {
        return (String) get(26);
    }

    /**
     * Setter for <code>TNW.user.lubrowserpath</code>. ??
     */
    public void setLubrowserpath(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>TNW.user.lubrowserpath</code>. ??
     */
    public String getLubrowserpath() {
        return (String) get(27);
    }

    /**
     * Setter for <code>TNW.user.luhomepage</code>. ??
     */
    public void setLuhomepage(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>TNW.user.luhomepage</code>. ??
     */
    public String getLuhomepage() {
        return (String) get(28);
    }

    /**
     * Setter for <code>TNW.user.lucorpid</code>. ??id
     */
    public void setLucorpid(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>TNW.user.lucorpid</code>. ??id
     */
    public String getLucorpid() {
        return (String) get(29);
    }

    /**
     * Setter for <code>TNW.user.lushopseq</code>.
     */
    public void setLushopseq(Integer value) {
        set(30, value);
    }

    /**
     * Getter for <code>TNW.user.lushopseq</code>.
     */
    public Integer getLushopseq() {
        return (Integer) get(30);
    }

    /**
     * Setter for <code>TNW.user.luorgid</code>. ????
     */
    public void setLuorgid(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>TNW.user.luorgid</code>. ????
     */
    public String getLuorgid() {
        return (String) get(31);
    }

    /**
     * Setter for <code>TNW.user.lumodiuserid</code>. ????
     */
    public void setLumodiuserid(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>TNW.user.lumodiuserid</code>. ????
     */
    public String getLumodiuserid() {
        return (String) get(32);
    }

    /**
     * Setter for <code>TNW.user.organization_id</code>. ???
     */
    public void setOrganizationId(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>TNW.user.organization_id</code>. ???
     */
    public String getOrganizationId() {
        return (String) get(33);
    }

    /**
     * Setter for <code>TNW.user.lupagerows</code>. ??id
     */
    public void setLupagerows(Integer value) {
        set(34, value);
    }

    /**
     * Getter for <code>TNW.user.lupagerows</code>. ??id
     */
    public Integer getLupagerows() {
        return (Integer) get(34);
    }

    /**
     * Setter for <code>TNW.user.lugxtime</code>.
     */
    public void setLugxtime(LocalDateTime value) {
        set(35, value);
    }

    /**
     * Getter for <code>TNW.user.lugxtime</code>.
     */
    public LocalDateTime getLugxtime() {
        return (LocalDateTime) get(35);
    }

    /**
     * Setter for <code>TNW.user.last_password_fail_time</code>. ??????????
     */
    public void setLastPasswordFailTime(LocalDateTime value) {
        set(36, value);
    }

    /**
     * Getter for <code>TNW.user.last_password_fail_time</code>. ??????????
     */
    public LocalDateTime getLastPasswordFailTime() {
        return (LocalDateTime) get(36);
    }

    /**
     * Setter for <code>TNW.user.last_password_reset_time</code>. ??????????
     */
    public void setLastPasswordResetTime(LocalDateTime value) {
        set(37, value);
    }

    /**
     * Getter for <code>TNW.user.last_password_reset_time</code>. ??????????
     */
    public LocalDateTime getLastPasswordResetTime() {
        return (LocalDateTime) get(37);
    }

    /**
     * Setter for <code>TNW.user.approval_status</code>. ??????
     */
    public void setApprovalStatus(UserApprovalStatus value) {
        set(38, value);
    }

    /**
     * Getter for <code>TNW.user.approval_status</code>. ??????
     */
    public UserApprovalStatus getApprovalStatus() {
        return (UserApprovalStatus) get(38);
    }

    /**
     * Setter for <code>TNW.user.updated_time</code>. ??????
     */
    public void setUpdatedTime(LocalDateTime value) {
        set(39, value);
    }

    /**
     * Getter for <code>TNW.user.updated_time</code>. ??????
     */
    public LocalDateTime getUpdatedTime() {
        return (LocalDateTime) get(39);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(String luuserid, String luusername, String luemail, String lupwd, String luoldpwd, String lumobile, String luphone, String luworkercode, String luusertype, LocalDateTime luregtime, LocalDateTime lulastlogtime, String lulastlogip, String luheadpic, String positionId, String positionName, String branchNo, String branchNm, String pointpraiseNo, String messageNo, String commentNo, String lubrowsertype, String luflag, Boolean luactive, String lusex, String lulogintoken, String token, String luenabled, String lubrowserpath, String luhomepage, String lucorpid, Integer lushopseq, String luorgid, String lumodiuserid, String organizationId, Integer lupagerows, LocalDateTime lugxtime, LocalDateTime lastPasswordFailTime, LocalDateTime lastPasswordResetTime, UserApprovalStatus approvalStatus, LocalDateTime updatedTime) {
        super(User.USER);

        set(0, luuserid);
        set(1, luusername);
        set(2, luemail);
        set(3, lupwd);
        set(4, luoldpwd);
        set(5, lumobile);
        set(6, luphone);
        set(7, luworkercode);
        set(8, luusertype);
        set(9, luregtime);
        set(10, lulastlogtime);
        set(11, lulastlogip);
        set(12, luheadpic);
        set(13, positionId);
        set(14, positionName);
        set(15, branchNo);
        set(16, branchNm);
        set(17, pointpraiseNo);
        set(18, messageNo);
        set(19, commentNo);
        set(20, lubrowsertype);
        set(21, luflag);
        set(22, luactive);
        set(23, lusex);
        set(24, lulogintoken);
        set(25, token);
        set(26, luenabled);
        set(27, lubrowserpath);
        set(28, luhomepage);
        set(29, lucorpid);
        set(30, lushopseq);
        set(31, luorgid);
        set(32, lumodiuserid);
        set(33, organizationId);
        set(34, lupagerows);
        set(35, lugxtime);
        set(36, lastPasswordFailTime);
        set(37, lastPasswordResetTime);
        set(38, approvalStatus);
        set(39, updatedTime);
    }
}
