/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.records;


import com.jic.tnw.db.mysql.tables.UserOrg;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * ????????
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserOrgRecord extends UpdatableRecordImpl<UserOrgRecord> implements Record8<Integer, Integer, Integer, String, Integer, LocalDateTime, Integer, LocalDateTime> {

    private static final long serialVersionUID = -1885961494;

    /**
     * Setter for <code>TNW.user_org.id</code>. ID
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TNW.user_org.id</code>. ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TNW.user_org.user_id</code>. ??ID
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>TNW.user_org.user_id</code>. ??ID
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>TNW.user_org.org_id</code>. ????id
     */
    public void setOrgId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>TNW.user_org.org_id</code>. ????id
     */
    public Integer getOrgId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>TNW.user_org.org_code</code>. ????????
     */
    public void setOrgCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>TNW.user_org.org_code</code>. ????????
     */
    public String getOrgCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>TNW.user_org.created_user_id</code>. ????ID
     */
    public void setCreatedUserId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>TNW.user_org.created_user_id</code>. ????ID
     */
    public Integer getCreatedUserId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>TNW.user_org.created_time</code>. ????
     */
    public void setCreatedTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>TNW.user_org.created_time</code>. ????
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>TNW.user_org.last_upd_user_id</code>. ?????
     */
    public void setLastUpdUserId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>TNW.user_org.last_upd_user_id</code>. ?????
     */
    public Integer getLastUpdUserId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>TNW.user_org.last_upd_time</code>. ??????
     */
    public void setLastUpdTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>TNW.user_org.last_upd_time</code>. ??????
     */
    public LocalDateTime getLastUpdTime() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, String, Integer, LocalDateTime, Integer, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, String, Integer, LocalDateTime, Integer, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserOrg.USER_ORG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserOrg.USER_ORG.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserOrg.USER_ORG.ORG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserOrg.USER_ORG.ORG_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return UserOrg.USER_ORG.CREATED_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return UserOrg.USER_ORG.CREATED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return UserOrg.USER_ORG.LAST_UPD_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return UserOrg.USER_ORG.LAST_UPD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getOrgCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getCreatedUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getLastUpdUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getLastUpdTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOrgCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getCreatedUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getLastUpdUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getLastUpdTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrgRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrgRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrgRecord value3(Integer value) {
        setOrgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrgRecord value4(String value) {
        setOrgCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrgRecord value5(Integer value) {
        setCreatedUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrgRecord value6(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrgRecord value7(Integer value) {
        setLastUpdUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrgRecord value8(LocalDateTime value) {
        setLastUpdTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserOrgRecord values(Integer value1, Integer value2, Integer value3, String value4, Integer value5, LocalDateTime value6, Integer value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserOrgRecord
     */
    public UserOrgRecord() {
        super(UserOrg.USER_ORG);
    }

    /**
     * Create a detached, initialised UserOrgRecord
     */
    public UserOrgRecord(Integer id, Integer userId, Integer orgId, String orgCode, Integer createdUserId, LocalDateTime createdTime, Integer lastUpdUserId, LocalDateTime lastUpdTime) {
        super(UserOrg.USER_ORG);

        set(0, id);
        set(1, userId);
        set(2, orgId);
        set(3, orgCode);
        set(4, createdUserId);
        set(5, createdTime);
        set(6, lastUpdUserId);
        set(7, lastUpdTime);
    }
}
