/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.daos;


import com.jic.tnw.db.mysql.tables.Org;
import com.jic.tnw.db.mysql.tables.records.OrgRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * ????
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class OrgDao extends DAOImpl<OrgRecord, com.jic.tnw.db.mysql.tables.pojos.Org, Integer> {

    /**
     * Create a new OrgDao without any configuration
     */
    public OrgDao() {
        super(Org.ORG, com.jic.tnw.db.mysql.tables.pojos.Org.class);
    }

    /**
     * Create a new OrgDao with an attached configuration
     */
    @Autowired
    public OrgDao(Configuration configuration) {
        super(Org.ORG, com.jic.tnw.db.mysql.tables.pojos.Org.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.jic.tnw.db.mysql.tables.pojos.Org object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Org> fetchById(Integer... values) {
        return fetch(Org.ORG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.jic.tnw.db.mysql.tables.pojos.Org fetchOneById(Integer value) {
        return fetchOne(Org.ORG.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Org> fetchByName(String... values) {
        return fetch(Org.ORG.NAME, values);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Org> fetchByParentId(Integer... values) {
        return fetch(Org.ORG.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>children_num IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Org> fetchByChildrenNum(Integer... values) {
        return fetch(Org.ORG.CHILDREN_NUM, values);
    }

    /**
     * Fetch records that have <code>depth IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Org> fetchByDepth(Integer... values) {
        return fetch(Org.ORG.DEPTH, values);
    }

    /**
     * Fetch records that have <code>seq IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Org> fetchBySeq(Integer... values) {
        return fetch(Org.ORG.SEQ, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Org> fetchByDescription(String... values) {
        return fetch(Org.ORG.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Org> fetchByCode(String... values) {
        return fetch(Org.ORG.CODE, values);
    }

    /**
     * Fetch a unique record that has <code>code = value</code>
     */
    public com.jic.tnw.db.mysql.tables.pojos.Org fetchOneByCode(String value) {
        return fetchOne(Org.ORG.CODE, value);
    }

    /**
     * Fetch records that have <code>org_code IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Org> fetchByOrgCode(String... values) {
        return fetch(Org.ORG.ORG_CODE, values);
    }

    /**
     * Fetch a unique record that has <code>org_code = value</code>
     */
    public com.jic.tnw.db.mysql.tables.pojos.Org fetchOneByOrgCode(String value) {
        return fetchOne(Org.ORG.ORG_CODE, value);
    }

    /**
     * Fetch records that have <code>created_user_id IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Org> fetchByCreatedUserId(Integer... values) {
        return fetch(Org.ORG.CREATED_USER_ID, values);
    }

    /**
     * Fetch records that have <code>created_time IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Org> fetchByCreatedTime(LocalDateTime... values) {
        return fetch(Org.ORG.CREATED_TIME, values);
    }

    /**
     * Fetch records that have <code>last_upd_user_id IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Org> fetchByLastUpdUserId(Integer... values) {
        return fetch(Org.ORG.LAST_UPD_USER_ID, values);
    }

    /**
     * Fetch records that have <code>last_upd_time IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Org> fetchByLastUpdTime(LocalDateTime... values) {
        return fetch(Org.ORG.LAST_UPD_TIME, values);
    }

    /**
     * Fetch records that have <code>sync_id IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Org> fetchBySyncId(Integer... values) {
        return fetch(Org.ORG.SYNC_ID, values);
    }
}
