/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.daos;


import com.jic.tnw.db.mysql.tables.PostMember;
import com.jic.tnw.db.mysql.tables.records.PostMemberRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * ????
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class PostMemberDao extends DAOImpl<PostMemberRecord, com.jic.tnw.db.mysql.tables.pojos.PostMember, Integer> {

    /**
     * Create a new PostMemberDao without any configuration
     */
    public PostMemberDao() {
        super(PostMember.POST_MEMBER, com.jic.tnw.db.mysql.tables.pojos.PostMember.class);
    }

    /**
     * Create a new PostMemberDao with an attached configuration
     */
    @Autowired
    public PostMemberDao(Configuration configuration) {
        super(PostMember.POST_MEMBER, com.jic.tnw.db.mysql.tables.pojos.PostMember.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.jic.tnw.db.mysql.tables.pojos.PostMember object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.PostMember> fetchById(Integer... values) {
        return fetch(PostMember.POST_MEMBER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.jic.tnw.db.mysql.tables.pojos.PostMember fetchOneById(Integer value) {
        return fetchOne(PostMember.POST_MEMBER.ID, value);
    }

    /**
     * Fetch records that have <code>post_id IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.PostMember> fetchByPostId(Integer... values) {
        return fetch(PostMember.POST_MEMBER.POST_ID, values);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.PostMember> fetchByUserId(Integer... values) {
        return fetch(PostMember.POST_MEMBER.USER_ID, values);
    }

    /**
     * Fetch records that have <code>created_user_id IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.PostMember> fetchByCreatedUserId(Integer... values) {
        return fetch(PostMember.POST_MEMBER.CREATED_USER_ID, values);
    }

    /**
     * Fetch records that have <code>created_time IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.PostMember> fetchByCreatedTime(LocalDateTime... values) {
        return fetch(PostMember.POST_MEMBER.CREATED_TIME, values);
    }

    /**
     * Fetch records that have <code>last_upd_user_id IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.PostMember> fetchByLastUpdUserId(Integer... values) {
        return fetch(PostMember.POST_MEMBER.LAST_UPD_USER_ID, values);
    }

    /**
     * Fetch records that have <code>last_upd_time IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.PostMember> fetchByLastUpdTime(LocalDateTime... values) {
        return fetch(PostMember.POST_MEMBER.LAST_UPD_TIME, values);
    }
}
