/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.daos;


import com.jic.tnw.db.mysql.tables.Post;
import com.jic.tnw.db.mysql.tables.records.PostRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * ??
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class PostDao extends DAOImpl<PostRecord, com.jic.tnw.db.mysql.tables.pojos.Post, Integer> {

    /**
     * Create a new PostDao without any configuration
     */
    public PostDao() {
        super(Post.POST, com.jic.tnw.db.mysql.tables.pojos.Post.class);
    }

    /**
     * Create a new PostDao with an attached configuration
     */
    @Autowired
    public PostDao(Configuration configuration) {
        super(Post.POST, com.jic.tnw.db.mysql.tables.pojos.Post.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.jic.tnw.db.mysql.tables.pojos.Post object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Post> fetchById(Integer... values) {
        return fetch(Post.POST.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.jic.tnw.db.mysql.tables.pojos.Post fetchOneById(Integer value) {
        return fetchOne(Post.POST.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Post> fetchByName(String... values) {
        return fetch(Post.POST.NAME, values);
    }

    /**
     * Fetch records that have <code>group_id IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Post> fetchByGroupId(Integer... values) {
        return fetch(Post.POST.GROUP_ID, values);
    }

    /**
     * Fetch records that have <code>seq IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Post> fetchBySeq(Integer... values) {
        return fetch(Post.POST.SEQ, values);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Post> fetchByCode(String... values) {
        return fetch(Post.POST.CODE, values);
    }

    /**
     * Fetch records that have <code>created_user_id IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Post> fetchByCreatedUserId(Integer... values) {
        return fetch(Post.POST.CREATED_USER_ID, values);
    }

    /**
     * Fetch records that have <code>created_time IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Post> fetchByCreatedTime(LocalDateTime... values) {
        return fetch(Post.POST.CREATED_TIME, values);
    }

    /**
     * Fetch records that have <code>last_upd_user_id IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Post> fetchByLastUpdUserId(Integer... values) {
        return fetch(Post.POST.LAST_UPD_USER_ID, values);
    }

    /**
     * Fetch records that have <code>last_upd_time IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.Post> fetchByLastUpdTime(LocalDateTime... values) {
        return fetch(Post.POST.LAST_UPD_TIME, values);
    }
}
