/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.daos;


import com.jic.tnw.db.mysql.enums.UserApprovalStatus;
import com.jic.tnw.db.mysql.tables.User;
import com.jic.tnw.db.mysql.tables.records.UserRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.time.LocalDateTime;
import java.util.List;


/**
 * ???
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UserDao extends DAOImpl<UserRecord, com.jic.tnw.db.mysql.tables.pojos.User, String> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER, com.jic.tnw.db.mysql.tables.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    @Autowired
    public UserDao(Configuration configuration) {
        super(User.USER, com.jic.tnw.db.mysql.tables.pojos.User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.jic.tnw.db.mysql.tables.pojos.User object) {
        return object.getLuuserid();
    }

    /**
     * Fetch records that have <code>luuserid IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLuuserid(String... values) {
        return fetch(User.USER.LUUSERID, values);
    }

    /**
     * Fetch a unique record that has <code>luuserid = value</code>
     */
    public com.jic.tnw.db.mysql.tables.pojos.User fetchOneByLuuserid(String value) {
        return fetchOne(User.USER.LUUSERID, value);
    }

    /**
     * Fetch records that have <code>luusername IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLuusername(String... values) {
        return fetch(User.USER.LUUSERNAME, values);
    }

    /**
     * Fetch a unique record that has <code>luusername = value</code>
     */
    public com.jic.tnw.db.mysql.tables.pojos.User fetchOneByLuusername(String value) {
        return fetchOne(User.USER.LUUSERNAME, value);
    }

    /**
     * Fetch records that have <code>luemail IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLuemail(String... values) {
        return fetch(User.USER.LUEMAIL, values);
    }

    /**
     * Fetch records that have <code>lupwd IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLupwd(String... values) {
        return fetch(User.USER.LUPWD, values);
    }

    /**
     * Fetch records that have <code>luoldpwd IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLuoldpwd(String... values) {
        return fetch(User.USER.LUOLDPWD, values);
    }

    /**
     * Fetch records that have <code>lumobile IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLumobile(String... values) {
        return fetch(User.USER.LUMOBILE, values);
    }

    /**
     * Fetch records that have <code>luphone IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLuphone(String... values) {
        return fetch(User.USER.LUPHONE, values);
    }

    /**
     * Fetch records that have <code>luworkercode IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLuworkercode(String... values) {
        return fetch(User.USER.LUWORKERCODE, values);
    }

    /**
     * Fetch records that have <code>luusertype IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLuusertype(String... values) {
        return fetch(User.USER.LUUSERTYPE, values);
    }

    /**
     * Fetch records that have <code>luregtime IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLuregtime(LocalDateTime... values) {
        return fetch(User.USER.LUREGTIME, values);
    }

    /**
     * Fetch records that have <code>lulastlogtime IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLulastlogtime(LocalDateTime... values) {
        return fetch(User.USER.LULASTLOGTIME, values);
    }

    /**
     * Fetch records that have <code>lulastlogip IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLulastlogip(String... values) {
        return fetch(User.USER.LULASTLOGIP, values);
    }

    /**
     * Fetch records that have <code>luheadpic IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLuheadpic(String... values) {
        return fetch(User.USER.LUHEADPIC, values);
    }

    /**
     * Fetch records that have <code>position_id IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByPositionId(String... values) {
        return fetch(User.USER.POSITION_ID, values);
    }

    /**
     * Fetch records that have <code>position_name IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByPositionName(String... values) {
        return fetch(User.USER.POSITION_NAME, values);
    }

    /**
     * Fetch records that have <code>branch_no IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByBranchNo(String... values) {
        return fetch(User.USER.BRANCH_NO, values);
    }

    /**
     * Fetch records that have <code>branch_nm IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByBranchNm(String... values) {
        return fetch(User.USER.BRANCH_NM, values);
    }

    /**
     * Fetch records that have <code>pointpraise_no IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByPointpraiseNo(String... values) {
        return fetch(User.USER.POINTPRAISE_NO, values);
    }

    /**
     * Fetch records that have <code>message_no IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByMessageNo(String... values) {
        return fetch(User.USER.MESSAGE_NO, values);
    }

    /**
     * Fetch records that have <code>comment_no IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByCommentNo(String... values) {
        return fetch(User.USER.COMMENT_NO, values);
    }

    /**
     * Fetch records that have <code>lubrowsertype IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLubrowsertype(String... values) {
        return fetch(User.USER.LUBROWSERTYPE, values);
    }

    /**
     * Fetch records that have <code>luflag IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLuflag(String... values) {
        return fetch(User.USER.LUFLAG, values);
    }

    /**
     * Fetch records that have <code>luactive IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLuactive(Boolean... values) {
        return fetch(User.USER.LUACTIVE, values);
    }

    /**
     * Fetch records that have <code>lusex IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLusex(String... values) {
        return fetch(User.USER.LUSEX, values);
    }

    /**
     * Fetch records that have <code>lulogintoken IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLulogintoken(String... values) {
        return fetch(User.USER.LULOGINTOKEN, values);
    }

    /**
     * Fetch records that have <code>token IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByToken(String... values) {
        return fetch(User.USER.TOKEN, values);
    }

    /**
     * Fetch records that have <code>luenabled IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLuenabled(String... values) {
        return fetch(User.USER.LUENABLED, values);
    }

    /**
     * Fetch records that have <code>lubrowserpath IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLubrowserpath(String... values) {
        return fetch(User.USER.LUBROWSERPATH, values);
    }

    /**
     * Fetch records that have <code>luhomepage IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLuhomepage(String... values) {
        return fetch(User.USER.LUHOMEPAGE, values);
    }

    /**
     * Fetch records that have <code>lucorpid IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLucorpid(String... values) {
        return fetch(User.USER.LUCORPID, values);
    }

    /**
     * Fetch records that have <code>lushopseq IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLushopseq(Integer... values) {
        return fetch(User.USER.LUSHOPSEQ, values);
    }

    /**
     * Fetch records that have <code>luorgid IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLuorgid(String... values) {
        return fetch(User.USER.LUORGID, values);
    }

    /**
     * Fetch records that have <code>lumodiuserid IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLumodiuserid(String... values) {
        return fetch(User.USER.LUMODIUSERID, values);
    }

    /**
     * Fetch records that have <code>organization_id IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByOrganizationId(String... values) {
        return fetch(User.USER.ORGANIZATION_ID, values);
    }

    /**
     * Fetch records that have <code>lupagerows IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLupagerows(Integer... values) {
        return fetch(User.USER.LUPAGEROWS, values);
    }

    /**
     * Fetch records that have <code>lugxtime IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLugxtime(LocalDateTime... values) {
        return fetch(User.USER.LUGXTIME, values);
    }

    /**
     * Fetch records that have <code>last_password_fail_time IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLastPasswordFailTime(LocalDateTime... values) {
        return fetch(User.USER.LAST_PASSWORD_FAIL_TIME, values);
    }

    /**
     * Fetch records that have <code>last_password_reset_time IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByLastPasswordResetTime(LocalDateTime... values) {
        return fetch(User.USER.LAST_PASSWORD_RESET_TIME, values);
    }

    /**
     * Fetch records that have <code>approval_status IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByApprovalStatus(UserApprovalStatus... values) {
        return fetch(User.USER.APPROVAL_STATUS, values);
    }

    /**
     * Fetch records that have <code>updated_time IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.User> fetchByUpdatedTime(LocalDateTime... values) {
        return fetch(User.USER.UPDATED_TIME, values);
    }
}
