/*
 * This file is generated by jOOQ.
*/
package com.jic.tnw.db.mysql.tables.daos;


import com.jic.tnw.db.mysql.enums.UserProfileGender;
import com.jic.tnw.db.mysql.tables.UserProfile;
import com.jic.tnw.db.mysql.tables.records.UserProfileRecord;

import java.sql.Date;
import java.time.LocalDate;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * ?????
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UserProfileDao extends DAOImpl<UserProfileRecord, com.jic.tnw.db.mysql.tables.pojos.UserProfile, Integer> {

    /**
     * Create a new UserProfileDao without any configuration
     */
    public UserProfileDao() {
        super(UserProfile.USER_PROFILE, com.jic.tnw.db.mysql.tables.pojos.UserProfile.class);
    }

    /**
     * Create a new UserProfileDao with an attached configuration
     */
    @Autowired
    public UserProfileDao(Configuration configuration) {
        super(UserProfile.USER_PROFILE, com.jic.tnw.db.mysql.tables.pojos.UserProfile.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.jic.tnw.db.mysql.tables.pojos.UserProfile object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchById(Integer... values) {
        return fetch(UserProfile.USER_PROFILE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.jic.tnw.db.mysql.tables.pojos.UserProfile fetchOneById(Integer value) {
        return fetchOne(UserProfile.USER_PROFILE.ID, value);
    }

    /**
     * Fetch records that have <code>idcard IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByIdcard(String... values) {
        return fetch(UserProfile.USER_PROFILE.IDCARD, values);
    }

    /**
     * Fetch records that have <code>gender IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByGender(UserProfileGender... values) {
        return fetch(UserProfile.USER_PROFILE.GENDER, values);
    }

    /**
     * Fetch records that have <code>iam IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByIam(String... values) {
        return fetch(UserProfile.USER_PROFILE.IAM, values);
    }

    /**
     * Fetch records that have <code>birthday IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByBirthday(Date... values) {
        return fetch(UserProfile.USER_PROFILE.BIRTHDAY, values);
    }

    /**
     * Fetch records that have <code>city IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByCity(String... values) {
        return fetch(UserProfile.USER_PROFILE.CITY, values);
    }

    /**
     * Fetch records that have <code>qq IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByQq(String... values) {
        return fetch(UserProfile.USER_PROFILE.QQ, values);
    }

    /**
     * Fetch records that have <code>signature IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchBySignature(String... values) {
        return fetch(UserProfile.USER_PROFILE.SIGNATURE, values);
    }

    /**
     * Fetch records that have <code>about IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByAbout(String... values) {
        return fetch(UserProfile.USER_PROFILE.ABOUT, values);
    }

    /**
     * Fetch records that have <code>company IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByCompany(String... values) {
        return fetch(UserProfile.USER_PROFILE.COMPANY, values);
    }

    /**
     * Fetch records that have <code>job IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByJob(String... values) {
        return fetch(UserProfile.USER_PROFILE.JOB, values);
    }

    /**
     * Fetch records that have <code>school IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchBySchool(String... values) {
        return fetch(UserProfile.USER_PROFILE.SCHOOL, values);
    }

    /**
     * Fetch records that have <code>class IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByClass(String... values) {
        return fetch(UserProfile.USER_PROFILE.CLASS, values);
    }

    /**
     * Fetch records that have <code>weibo IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByWeibo(String... values) {
        return fetch(UserProfile.USER_PROFILE.WEIBO, values);
    }

    /**
     * Fetch records that have <code>weixin IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByWeixin(String... values) {
        return fetch(UserProfile.USER_PROFILE.WEIXIN, values);
    }

    /**
     * Fetch records that have <code>is_QQ_Public IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByIsQqPublic(Integer... values) {
        return fetch(UserProfile.USER_PROFILE.IS_QQ_PUBLIC, values);
    }

    /**
     * Fetch records that have <code>is_Weixin_Public IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByIsWeixinPublic(Integer... values) {
        return fetch(UserProfile.USER_PROFILE.IS_WEIXIN_PUBLIC, values);
    }

    /**
     * Fetch records that have <code>is_Weibo_Public IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByIsWeiboPublic(Integer... values) {
        return fetch(UserProfile.USER_PROFILE.IS_WEIBO_PUBLIC, values);
    }

    /**
     * Fetch records that have <code>site IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchBySite(String... values) {
        return fetch(UserProfile.USER_PROFILE.SITE, values);
    }

    /**
     * Fetch records that have <code>field1_int IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField1Int(Integer... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD1_INT, values);
    }

    /**
     * Fetch records that have <code>field2_int IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField2Int(Integer... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD2_INT, values);
    }

    /**
     * Fetch records that have <code>field3_int IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField3Int(Integer... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD3_INT, values);
    }

    /**
     * Fetch records that have <code>field4_int IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField4Int(Integer... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD4_INT, values);
    }

    /**
     * Fetch records that have <code>field5_int IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField5Int(Integer... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD5_INT, values);
    }

    /**
     * Fetch records that have <code>field1_date IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField1Date(LocalDate... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD1_DATE, values);
    }

    /**
     * Fetch records that have <code>field2_date IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField2Date(LocalDate... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD2_DATE, values);
    }

    /**
     * Fetch records that have <code>field3_date IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField3Date(LocalDate... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD3_DATE, values);
    }

    /**
     * Fetch records that have <code>field4_date IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField4Date(LocalDate... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD4_DATE, values);
    }

    /**
     * Fetch records that have <code>field5_date IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField5Date(LocalDate... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD5_DATE, values);
    }

    /**
     * Fetch records that have <code>field1_float IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField1Float(Double... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD1_FLOAT, values);
    }

    /**
     * Fetch records that have <code>field2_float IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField2Float(Double... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD2_FLOAT, values);
    }

    /**
     * Fetch records that have <code>field3_float IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField3Float(Double... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD3_FLOAT, values);
    }

    /**
     * Fetch records that have <code>field4_float IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField4Float(Double... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD4_FLOAT, values);
    }

    /**
     * Fetch records that have <code>field5_float IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField5Float(Double... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD5_FLOAT, values);
    }

    /**
     * Fetch records that have <code>Field1_varchar IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField1Varchar(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD1_VARCHAR, values);
    }

    /**
     * Fetch records that have <code>Field2_varchar IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField2Varchar(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD2_VARCHAR, values);
    }

    /**
     * Fetch records that have <code>Field3_varchar IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField3Varchar(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD3_VARCHAR, values);
    }

    /**
     * Fetch records that have <code>Field4_varchar IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField4Varchar(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD4_VARCHAR, values);
    }

    /**
     * Fetch records that have <code>Field5_varchar IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField5Varchar(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD5_VARCHAR, values);
    }

    /**
     * Fetch records that have <code>Field6_varchar IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField6Varchar(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD6_VARCHAR, values);
    }

    /**
     * Fetch records that have <code>Field7_varchar IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField7Varchar(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD7_VARCHAR, values);
    }

    /**
     * Fetch records that have <code>Field8_varchar IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField8Varchar(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD8_VARCHAR, values);
    }

    /**
     * Fetch records that have <code>Field9_varchar IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField9Varchar(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD9_VARCHAR, values);
    }

    /**
     * Fetch records that have <code>Field10_varchar IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField10Varchar(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD10_VARCHAR, values);
    }

    /**
     * Fetch records that have <code>Field1_text IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField1Text(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD1_TEXT, values);
    }

    /**
     * Fetch records that have <code>Field2_text IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField2Text(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD2_TEXT, values);
    }

    /**
     * Fetch records that have <code>Field3_text IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField3Text(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD3_TEXT, values);
    }

    /**
     * Fetch records that have <code>Field4_text IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField4Text(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD4_TEXT, values);
    }

    /**
     * Fetch records that have <code>Field5_text IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField5Text(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD5_TEXT, values);
    }

    /**
     * Fetch records that have <code>Field6_text IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField6Text(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD6_TEXT, values);
    }

    /**
     * Fetch records that have <code>Field7_text IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField7Text(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD7_TEXT, values);
    }

    /**
     * Fetch records that have <code>Field8_text IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField8Text(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD8_TEXT, values);
    }

    /**
     * Fetch records that have <code>Field9_text IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField9Text(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD9_TEXT, values);
    }

    /**
     * Fetch records that have <code>Field10_text IN (values)</code>
     */
    public List<com.jic.tnw.db.mysql.tables.pojos.UserProfile> fetchByField10Text(String... values) {
        return fetch(UserProfile.USER_PROFILE.FIELD10_TEXT, values);
    }
}
